// <auto-generated/>
// Public API skeleton for: /Users/jumar/Desktop/Avalonia.DBus/src/Avalonia.DBus/Avalonia.DBus.csproj
// Assembly: Avalonia.DBus
// Generated (UTC): 2026-02-09T10:46:03.2493790+00:00
#nullable enable

namespace Avalonia.DBus
{
    public static partial class DBusBuiltIns
    {
        public static bool EnableGetNameOwner { get; set; } = true;
        public static bool EnableIntrospectableInterface { get; set; } = true;
        public static bool EnablePeerInterface { get; set; } = true;
        public static bool EnablePropertiesInterface { get; set; } = true;
    }

    public sealed partial class DBusConnection : IAsyncDisposable
    {
        public DBusWireConnection Wire { get; }
        public IDisposable RegisterObject(DBusObjectPath path, string iface, Func<DBusMessage, Task<DBusMessage>> handler, SynchronizationContext? synchronizationContext = null);
        public IDisposable RegisterObject(IDBusObject obj, SynchronizationContext? synchronizationContext = null);
        public Task ReleaseNameAsync(string name, CancellationToken cancellationToken = default);
        public Task<DBusMessage> CallMethodAsync(string destination, DBusObjectPath path, string iface, string member, CancellationToken cancellationToken, params object[] args);
        public Task<DBusMessage> CallMethodAsync(string destination, DBusObjectPath path, string iface, string member, params object[] args);
        public Task<DBusRequestNameReply> RequestNameAsync(string name, DBusRequestNameFlags flags = 0, CancellationToken cancellationToken = default);
        public Task<IDisposable> SubscribeAsync(string? sender, DBusObjectPath? path, string iface, string member, Func<DBusMessage, Task> handler, SynchronizationContext? synchronizationContext = null);
        public Task<IDisposable> WatchNameOwnerChangedAsync(Action<string, string?, string?> handler, bool emitOnCapturedContext = true, string? sender = null);
        public Task<IDisposable> WatchNameOwnerChangedAsync(Func<string, string?, string?, Task> handler, bool emitOnCapturedContext = true, string? sender = null);
        public Task<string?> GetNameOwnerAsync(string name, CancellationToken cancellationToken = default);
        public Task<string?> GetUniqueNameAsync();
        public ValueTask DisposeAsync();
        public static Task<DBusConnection> ConnectAsync(string address, CancellationToken cancellationToken = default);
        public static Task<DBusConnection> ConnectSessionAsync(CancellationToken cancellationToken = default);
        public static Task<DBusConnection> ConnectSystemAsync(CancellationToken cancellationToken = default);
    }

    public partial class DBusException : Exception
    {
        public DBusException(string errorName, string? message, DBusMessage dbusMessage);
        public DBusMessage ErrorReply { get; }
        public string ErrorName { get; }
    }

    public sealed partial class DBusMessage
    {
        public bool IsError(string errorName);
        public bool IsMethodCall(string iface, string member);
        public bool IsSignal(string iface, string member);
        public DBusMessage CreateError(string errorName, string? errorMessage = null);
        public DBusMessage CreateReply(params object[] body);
        public DBusMessageFlags Flags { get; set; }
        public DBusMessageType Type { get; set; }
        public DBusObjectPath? Path { get; set; }
        public DBusSignature Signature { get; }
        public IReadOnlyList<object> Body { get; set; }
        public static DBusMessage CreateMethodCall(string destination, DBusObjectPath path, string iface, string member, params object[] body);
        public static DBusMessage CreateSignal(DBusObjectPath path, string iface, string member, params object[] body);
        public string? Destination { get; set; }
        public string? ErrorName { get; set; }
        public string? Interface { get; set; }
        public string? Member { get; set; }
        public string? Sender { get; set; }
        public uint ReplySerial { get; set; }
        public uint Serial { get; set; }
    }

    public enum DBusMessageFlags
    {
        AllowInteractiveAuthorization,
        NoAutoStart,
        NoReplyExpected,
        None,
    }

    public enum DBusMessageType
    {
        Error,
        Invalid,
        MethodCall,
        MethodReturn,
        Signal,
    }

    public sealed partial class DBusObject : ICollection<IDBusInterfaceHandler>, IDBusObject
    {
        public DBusObject(DBusObjectPath path);
        public DBusObject(string path);
        public bool Contains(IDBusInterfaceHandler item);
        public bool HasInterface(string name);
        public bool IsReadOnly { get; }
        public bool Remove(IDBusInterfaceHandler item);
        public bool TryGetProperty(string iface, string name, out DBusVariant value);
        public bool TrySetProperty(string iface, string name, DBusVariant value);
        public DBusObjectPath Path { get; }
        public Dictionary<string, DBusVariant> GetAllProperties(string iface);
        public IEnumerator<IDBusInterfaceHandler> GetEnumerator();
        public Task<DBusMessage> HandleMethodAsync(DBusMessage request);
        public int Count { get; }
        public string IntrospectXml { get; }
        public void Add(IDBusInterfaceHandler item);
        public void Clear();
        public void CopyTo(IDBusInterfaceHandler[] array, int arrayIndex);
        IEnumerator IEnumerable.GetEnumerator();
    }

    public partial struct DBusObjectPath : IEquatable<DBusObjectPath>
    {
        public DBusObjectPath(string value);
        public bool Equals(DBusObjectPath other);
        public override bool Equals(object? obj);
        public override int GetHashCode();
        public override string ToString();
        public static bool operator !=(DBusObjectPath left, DBusObjectPath right);
        public static bool operator ==(DBusObjectPath left, DBusObjectPath right);
        public static explicit operator DBusObjectPath(string value);
        public static implicit operator string(DBusObjectPath value);
        public string Value { get; }
    }

    public sealed partial class DBusObjectTree
    {
        public DBusObjectTree(string rootPath);
        public bool RemovePath(string path);
        public DBusObject AddPath(string path);
        public IDisposable Register(DBusConnection connection);
        public string Path { get; }
    }

    public enum DBusRequestNameFlags
    {
        AllowReplacement,
        DoNotQueue,
        None,
        ReplaceExisting,
    }

    public enum DBusRequestNameReply
    {
        AlreadyOwner,
        Exists,
        InQueue,
        PrimaryOwner,
    }

    public partial struct DBusSignature : IEquatable<DBusSignature>
    {
        public DBusSignature(string value);
        public bool Equals(DBusSignature other);
        public override bool Equals(object? obj);
        public override int GetHashCode();
        public override string ToString();
        public static bool operator !=(DBusSignature left, DBusSignature right);
        public static bool operator ==(DBusSignature left, DBusSignature right);
        public static explicit operator DBusSignature(string value);
        public static implicit operator string(DBusSignature value);
        public string Value { get; }
    }

    public sealed partial class DBusStruct : IReadOnlyList<object>
    {
        public DBusStruct(IEnumerable<object> fields);
        public DBusStruct(params object[] fields);
        public IEnumerator<object> GetEnumerator();
        public int Count { get; }
        public object this[int index] { get; }
        IEnumerator IEnumerable.GetEnumerator();
    }

    public partial class DBusUnixFd : IEquatable<DBusUnixFd>
    {
        public DBusUnixFd(int Fd);
        public int Fd { get; set; }
    }

    public sealed partial class DBusVariant
    {
        public DBusVariant(DBusSignature signature, object value);
        public DBusVariant(object value);
        public DBusSignature Signature { get; }
        public object Value { get; }
    }

    public sealed partial class DBusWireConnection : IAsyncDisposable
    {
        public IAsyncEnumerable<DBusMessage> ReceiveAsync(CancellationToken cancellationToken = default);
        public Task SendAsync(DBusMessage message, CancellationToken cancellationToken = default);
        public Task<DBusMessage> SendWithReplyAsync(DBusMessage message, CancellationToken cancellationToken = default);
        public Task<string?> GetUniqueNameAsync();
        public ValueTask DisposeAsync();
        public static Task<DBusWireConnection> ConnectAsync(string address, CancellationToken cancellationToken = default);
        public static Task<DBusWireConnection> ConnectSessionAsync(CancellationToken cancellationToken = default);
        public static Task<DBusWireConnection> ConnectSystemAsync(CancellationToken cancellationToken = default);
    }

    public partial interface IDBusInterfaceHandler
    {
        bool TryGetProperty(string name, out DBusVariant value);
        bool TrySetProperty(string name, DBusVariant value);
        DBusConnection Connection { get; }
        DBusObjectPath? Path { get; set; }
        Dictionary<string, DBusVariant> GetAllProperties();
        Task<DBusMessage> HandleMethodAsync(DBusMessage request);
        string InterfaceName { get; }
        string IntrospectXml { get; }
    }

    public partial interface IDBusObject
    {
        bool HasInterface(string name);
        bool TryGetProperty(string iface, string name, out DBusVariant value);
        bool TrySetProperty(string iface, string name, DBusVariant value);
        DBusObjectPath Path { get; }
        Dictionary<string, DBusVariant> GetAllProperties(string iface);
        Task<DBusMessage> HandleMethodAsync(DBusMessage request);
        string IntrospectXml { get; }
    }
}