using System.Collections.Concurrent;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Avalonia.DBus.PublicApiExtractor;

internal static class Program
{
    public static async Task<int> Main(string[] args)
    {
        try
        {
            var csprojPath = args.Length >= 1 ? args[0] : "src/Avalonia.DBus/Avalonia.DBus.csproj";
            var outputPath = args.Length >= 2 ? args[1] : "public-api-skeleton.cs";
            if (args.Length > 2) return Usage();

            var compilation = CreateCompilationFromCsproj(csprojPath);

            var lines = new List<string>(capacity: 16_384);
            lines.Add("// <auto-generated/>");
            lines.Add($"// Public API skeleton for: {Path.GetFullPath(csprojPath)}");
            lines.Add($"// Assembly: {compilation.AssemblyName}");
            lines.Add($"// Generated (UTC): {DateTimeOffset.UtcNow:O}");
            lines.Add("#nullable enable");
            lines.Add("");

            var typeFormat = new SymbolDisplayFormat(
                globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
                typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
                genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
                miscellaneousOptions:
                    SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                    SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                    SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

            var memberFormat = new SymbolDisplayFormat(
                globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
                typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
                genericsOptions:
                    SymbolDisplayGenericsOptions.IncludeTypeParameters |
                    SymbolDisplayGenericsOptions.IncludeVariance,
                memberOptions:
                    SymbolDisplayMemberOptions.IncludeContainingType |
                    SymbolDisplayMemberOptions.IncludeParameters |
                    SymbolDisplayMemberOptions.IncludeType |
                    SymbolDisplayMemberOptions.IncludeExplicitInterface,
                parameterOptions:
                    SymbolDisplayParameterOptions.IncludeType |
                    SymbolDisplayParameterOptions.IncludeName |
                    SymbolDisplayParameterOptions.IncludeDefaultValue |
                    SymbolDisplayParameterOptions.IncludeParamsRefOut |
                    SymbolDisplayParameterOptions.IncludeExtensionThis,
                propertyStyle: SymbolDisplayPropertyStyle.ShowReadWriteDescriptor,
                kindOptions: SymbolDisplayKindOptions.IncludeMemberKeyword,
                miscellaneousOptions:
                    SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                    SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                    SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

            // Build a tree of externally visible types grouped by namespace and containing type.
            var allTypes = new ConcurrentBag<INamedTypeSymbol>();
            CollectTypes(compilation.Assembly.GlobalNamespace, allTypes);

            var orderedTopLevelTypes = allTypes
                .Distinct(new NamedTypeSymbolComparer())
                .Where(t => t.ContainingType is null)
                .Where(t => !t.IsImplicitlyDeclared)
                .Where(IsExternallyVisibleType)
                .OrderBy(t => GetNamespaceName(t), StringComparer.Ordinal)
                .ThenBy(t => t.Name, StringComparer.Ordinal)
                .ToList();

            var byNamespace = orderedTopLevelTypes
                .GroupBy(GetNamespaceName, StringComparer.Ordinal)
                .OrderBy(g => g.Key, StringComparer.Ordinal)
                .ToList();

            foreach (var nsGroup in byNamespace)
            {
                var nsName = nsGroup.Key;
                if (nsName.Length == 0)
                {
                    // global namespace: emit types directly.
                    foreach (var t in nsGroup.OrderBy(t => t.ToDisplayString(typeFormat), StringComparer.Ordinal))
                    {
                        EmitType(lines, t, typeFormat, memberFormat, indentLevel: 0);
                        lines.Add("");
                    }
                    continue;
                }

                lines.Add($"namespace {nsName}");
                lines.Add("{");
                foreach (var t in nsGroup.OrderBy(t => t.ToDisplayString(typeFormat), StringComparer.Ordinal))
                {
                    EmitType(lines, t, typeFormat, memberFormat, indentLevel: 1);
                    lines.Add("");
                }
                lines.Add("}");
                lines.Add("");
            }

            Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath)) ?? ".");
            await File.WriteAllLinesAsync(outputPath, lines, Encoding.UTF8).ConfigureAwait(false);

            Console.WriteLine($"Wrote {lines.Count} lines to {outputPath}");
            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            return 1;
        }
    }

    private static int Usage()
    {
        Console.Error.WriteLine("Usage: dotnet run --project tools/Avalonia.DBus.PublicApiExtractor -- [csprojPath] [outputPath]");
        Console.Error.WriteLine("Defaults:");
        Console.Error.WriteLine("  csprojPath: src/Avalonia.DBus/Avalonia.DBus.csproj");
        Console.Error.WriteLine("  outputPath: public-api-skeleton.cs");
        return 2;
    }

    private static CSharpCompilation CreateCompilationFromCsproj(string csprojPath)
    {
        csprojPath = Path.GetFullPath(csprojPath);
        var projectDir = Path.GetDirectoryName(csprojPath) ?? ".";
        var assemblyName = Path.GetFileNameWithoutExtension(csprojPath);

        var removeGlobs = ReadCompileRemoveGlobs(csprojPath);

        var csFiles = Directory.EnumerateFiles(projectDir, "*.cs", SearchOption.AllDirectories)
            .Where(p => !IsUnderDirectory(p, "bin") && !IsUnderDirectory(p, "obj"))
            .Where(p => !MatchesAnyGlob(projectDir, p, removeGlobs))
            .ToList();

        var parseOptions = CSharpParseOptions.Default
            .WithLanguageVersion(LanguageVersion.Latest)
            .WithKind(SourceCodeKind.Regular);

        var trees = new List<SyntaxTree>(csFiles.Count);
        foreach (var file in csFiles.OrderBy(p => p, StringComparer.Ordinal))
        {
            var text = File.ReadAllText(file, Encoding.UTF8);
            trees.Add(CSharpSyntaxTree.ParseText(text, parseOptions, path: file));
        }

        var references = GetTrustedPlatformAssemblyReferences();

        var compilationOptions = new CSharpCompilationOptions(
            OutputKind.DynamicallyLinkedLibrary,
            optimizationLevel: OptimizationLevel.Release,
            allowUnsafe: true,
            nullableContextOptions: NullableContextOptions.Enable);

        var compilation = CSharpCompilation.Create(
            assemblyName,
            syntaxTrees: trees,
            references: references,
            options: compilationOptions);

        // Don't fail on compile errors; we only need symbol info for what Roslyn can bind.
        // Still print errors to help catch missing references if the API output looks wrong.
        var diags = compilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .Take(20)
            .ToList();
        foreach (var d in diags)
            Console.Error.WriteLine($"[compile] {d.Id}: {d.GetMessage()} ({d.Location.GetLineSpan().Path})");

        return compilation;
    }

    private static IReadOnlyList<string> ReadCompileRemoveGlobs(string csprojPath)
    {
        try
        {
            var doc = XDocument.Load(csprojPath);
            var remove = doc.Descendants().Where(e => e.Name.LocalName == "Compile")
                .Select(e => (string?)e.Attribute("Remove"))
                .Where(s => !string.IsNullOrWhiteSpace(s))
                .SelectMany(s => s!.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
                .ToList();

            return remove;
        }
        catch
        {
            return Array.Empty<string>();
        }
    }

    private static bool IsUnderDirectory(string path, string dirName)
    {
        var parts = Path.GetFullPath(path)
            .Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        return parts.Any(p => string.Equals(p, dirName, StringComparison.OrdinalIgnoreCase));
    }

    private static bool MatchesAnyGlob(string projectDir, string filePath, IReadOnlyList<string> globs)
    {
        if (globs.Count == 0) return false;
        var rel = Path.GetRelativePath(projectDir, filePath).Replace('\\', '/');
        foreach (var g in globs)
        {
            var re = GlobToRegex(g.Replace('\\', '/'));
            if (re.IsMatch(rel))
                return true;
        }
        return false;
    }

    private static Regex GlobToRegex(string glob)
    {
        // Minimal glob support: *, ?, ** (directory wildcard). Matches against forward-slash normalized relative paths.
        var sb = new StringBuilder();
        sb.Append("^");
        for (var i = 0; i < glob.Length; i++)
        {
            var c = glob[i];
            if (c == '*')
            {
                var isDoubleStar = i + 1 < glob.Length && glob[i + 1] == '*';
                if (isDoubleStar)
                {
                    sb.Append(".*");
                    i++;
                }
                else
                {
                    sb.Append("[^/]*");
                }
                continue;
            }

            if (c == '?')
            {
                sb.Append("[^/]");
                continue;
            }

            sb.Append(Regex.Escape(c.ToString()));
        }
        sb.Append("$");
        return new Regex(sb.ToString(), RegexOptions.CultureInvariant | RegexOptions.Compiled);
    }

    private static IReadOnlyList<MetadataReference> GetTrustedPlatformAssemblyReferences()
    {
        var tpa = (string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES");
        if (string.IsNullOrWhiteSpace(tpa))
            return Array.Empty<MetadataReference>();

        return tpa.Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Distinct(StringComparer.Ordinal)
            .Select(p => (MetadataReference)MetadataReference.CreateFromFile(p))
            .ToList();
    }

    private static void CollectTypes(INamespaceSymbol ns, ConcurrentBag<INamedTypeSymbol> allTypes)
    {
        foreach (var memberNs in ns.GetNamespaceMembers())
            CollectTypes(memberNs, allTypes);

        foreach (var type in ns.GetTypeMembers())
            CollectTypes(type, allTypes);
    }

    private static void CollectTypes(INamedTypeSymbol type, ConcurrentBag<INamedTypeSymbol> allTypes)
    {
        allTypes.Add(type);
        foreach (var nested in type.GetTypeMembers())
            CollectTypes(nested, allTypes);
    }

    private static bool IsExternallyVisibleType(INamedTypeSymbol t)
    {
        // A nested public type must have all containing types externally visible too.
        for (INamedTypeSymbol? cur = t; cur is not null; cur = cur.ContainingType)
        {
            if (!IsExternallyVisibleAccessibility(cur.DeclaredAccessibility))
                return false;
        }

        // Namespace types must be public to be externally visible.
        return t.ContainingType is not null || t.DeclaredAccessibility == Accessibility.Public;
    }

    private static bool IsExternallyVisibleMember(ISymbol m)
    {
        if (!IsExternallyVisibleAccessibility(m.DeclaredAccessibility))
            return false;

        // Skip synthesized accessors; properties/events will represent them.
        if (m is IMethodSymbol ms && ms.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet or MethodKind.EventAdd or MethodKind.EventRemove)
            return false;

        return true;
    }

    private static bool IsExternallyVisibleAccessibility(Accessibility a) =>
        a is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal;

    private static IEnumerable<IMethodSymbol> GetExplicitInterfaceImplementations(INamedTypeSymbol t)
    {
        if (!IsExternallyVisibleType(t))
            yield break;

        foreach (var m in t.GetMembers().OfType<IMethodSymbol>())
        {
            if (m.IsImplicitlyDeclared) continue;
            if (m.ExplicitInterfaceImplementations.Length == 0) continue;
            yield return m;
        }
    }

    private static string GetNamespaceName(INamedTypeSymbol t)
    {
        var ns = t.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "";
        // "global::X.Y" -> "X.Y", "global::" -> ""
        const string globalPrefix = "global::";
        if (ns.StartsWith(globalPrefix, StringComparison.Ordinal))
            ns = ns[globalPrefix.Length..];
        return ns;
    }

    private static void EmitType(List<string> lines, INamedTypeSymbol t, SymbolDisplayFormat typeFormat, SymbolDisplayFormat memberFormat, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);
        var nestedIndent = new string(' ', (indentLevel + 1) * 4);

        // Delegate types are emitted as single-line declarations.
        if (t.TypeKind == TypeKind.Delegate && t.DelegateInvokeMethod is { } invoke)
        {
            var decl = $"{indent}{GetAccessibilityKeyword(t.DeclaredAccessibility)} delegate {invoke.ReturnType.ToDisplayString(typeFormat)} {t.Name}{RenderTypeParameters(t)}{RenderParameters(invoke, typeFormat)}{RenderTypeParameterConstraints(t, typeFormat)};";
            lines.Add(decl.Trim());
            return;
        }

        var kindKeyword = t.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            TypeKind.Enum => "enum",
            _ => "type",
        };

        var typeMods = new List<string>();
        var accessibility = GetAccessibilityKeyword(t.DeclaredAccessibility);
        if (accessibility.Length != 0) typeMods.Add(accessibility);
        if (t.IsStatic && t.TypeKind == TypeKind.Class) typeMods.Add("static");
        if (t.IsAbstract && t.TypeKind == TypeKind.Class) typeMods.Add("abstract");
        if (t.IsSealed && t.TypeKind == TypeKind.Class && !t.IsStatic) typeMods.Add("sealed");
        if (t.TypeKind is TypeKind.Class or TypeKind.Struct or TypeKind.Interface) typeMods.Add("partial");

        var header = new StringBuilder();
        header.Append(indent);
        header.Append(string.Join(" ", typeMods.Where(s => s.Length != 0)));
        if (header.Length > indent.Length) header.Append(' ');
        header.Append(kindKeyword).Append(' ').Append(t.Name).Append(RenderTypeParameters(t));

        var bases = new List<string>();
        if (t.TypeKind == TypeKind.Class && t.BaseType is { } bt && bt.SpecialType != SpecialType.System_Object)
            bases.Add(bt.ToDisplayString(typeFormat));
        if (t.TypeKind != TypeKind.Enum)
            bases.AddRange(t.Interfaces.Select(i => i.ToDisplayString(typeFormat)));
        if (bases.Count != 0)
            header.Append(" : ").Append(string.Join(", ", bases.Distinct(StringComparer.Ordinal)));

        var constraints = RenderTypeParameterConstraints(t, typeFormat);
        lines.Add(header.ToString());
        if (constraints.Length != 0)
            lines.Add($"{indent}{constraints}");

        lines.Add($"{indent}{{");

        if (t.TypeKind == TypeKind.Enum)
        {
            var enumMembers = t.GetMembers()
                .OfType<IFieldSymbol>()
                .Where(f => f is { IsImplicitlyDeclared: false, HasConstantValue: true })
                .Where(f => f.DeclaredAccessibility == Accessibility.Public)
                .OrderBy(f => f.Name, StringComparer.Ordinal)
                .ToList();

            foreach (var f in enumMembers)
                lines.Add($"{nestedIndent}{f.Name},");

            lines.Add($"{indent}}}");
            return;
        }

        var members = t.GetMembers()
            .Where(m => !m.IsImplicitlyDeclared)
            .Where(m => m is not INamedTypeSymbol) // nested types handled separately
            .Where(m => IsExternallyVisibleMember(m))
            .Select(m => EmitMember(m, t, typeFormat, memberFormat, nestedIndent))
            .Where(s => s.Length != 0)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        foreach (var m in members)
            lines.Add(m);

        // Explicit interface implementations (callable via the interface) even though they're often private.
        var explicitMembers = GetExplicitInterfaceMembers(t)
            .Select(m => EmitMember(m, t, typeFormat, memberFormat, nestedIndent))
            .Where(s => s.Length != 0)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToList();

        foreach (var m in explicitMembers)
            lines.Add(m);

        // Nested types
        var nestedTypes = t.GetTypeMembers()
            .Where(nt => !nt.IsImplicitlyDeclared)
            .Where(IsExternallyVisibleType)
            .OrderBy(nt => nt.ToDisplayString(typeFormat), StringComparer.Ordinal)
            .ToList();

        if (nestedTypes.Count != 0 && (members.Count != 0 || explicitMembers.Count != 0))
            lines.Add("");

        foreach (var nt in nestedTypes)
        {
            EmitType(lines, nt, typeFormat, memberFormat, indentLevel + 1);
            lines.Add("");
        }

        // Trim extra blank line at end of type body.
        while (lines.Count > 0 && lines[^1].Length == 0)
            lines.RemoveAt(lines.Count - 1);

        lines.Add($"{indent}}}");
    }

    private static string EmitMember(ISymbol m, INamedTypeSymbol containingType, SymbolDisplayFormat typeFormat, SymbolDisplayFormat memberFormat, string indent)
    {
        // Signatures only: we intentionally do not emit method bodies.
        // The output is meant as an API surface reference, not a compilable implementation.
        var inInterface = containingType.TypeKind == TypeKind.Interface;
        switch (m)
        {
            case IFieldSymbol f:
                if (f.AssociatedSymbol is not null) return "";
                if (f.ContainingType.TypeKind == TypeKind.Enum) return "";
                return $"{indent}{RenderField(f, typeFormat)}";

            case IEventSymbol e:
                return $"{indent}{RenderEvent(e, typeFormat, inInterface)}";

            case IPropertySymbol p:
                return $"{indent}{RenderProperty(p, typeFormat, inInterface)}";

            case IMethodSymbol ms:
                if (ms.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet or MethodKind.EventAdd or MethodKind.EventRemove)
                    return "";
                return $"{indent}{RenderMethod(ms, containingType, typeFormat, memberFormat, inInterface)}";
        }

        return "";
    }

    private static IEnumerable<ISymbol> GetExplicitInterfaceMembers(INamedTypeSymbol t)
    {
        if (!IsExternallyVisibleType(t))
            yield break;

        foreach (var m in t.GetMembers())
        {
            if (m.IsImplicitlyDeclared) continue;
            switch (m)
            {
                case IMethodSymbol ms when ms.ExplicitInterfaceImplementations.Length != 0:
                    yield return ms;
                    break;
                case IPropertySymbol ps when ps.ExplicitInterfaceImplementations.Length != 0:
                    yield return ps;
                    break;
                case IEventSymbol es when es.ExplicitInterfaceImplementations.Length != 0:
                    yield return es;
                    break;
            }
        }
    }

    private static string RenderField(IFieldSymbol f, SymbolDisplayFormat typeFormat)
    {
        var mods = new List<string>();
        var acc = GetAccessibilityKeyword(f.DeclaredAccessibility);
        if (acc.Length != 0) mods.Add(acc);
        if (f.IsConst) mods.Add("const");
        else
        {
            if (f.IsStatic) mods.Add("static");
            if (f.IsReadOnly) mods.Add("readonly");
        }

        var sb = new StringBuilder();
        sb.Append(string.Join(" ", mods)).Append(' ');
        sb.Append(f.Type.ToDisplayString(typeFormat)).Append(' ').Append(f.Name);

        if (f.IsConst)
        {
            sb.Append(" = ").Append(RenderConstant(f.ConstantValue)).Append(';');
        }
        else
        {
            sb.Append(';');
        }

        return sb.ToString();
    }

    private static string RenderEvent(IEventSymbol e, SymbolDisplayFormat typeFormat, bool inInterface)
    {
        var mods = new List<string>();
        if (!inInterface)
        {
            var acc = e.ExplicitInterfaceImplementations.Length == 0 ? GetAccessibilityKeyword(e.DeclaredAccessibility) : "";
            if (acc.Length != 0) mods.Add(acc);
            if (e.IsStatic) mods.Add("static");
        }
        else
        {
            if (e.IsStatic) mods.Add("static");
            if (e.DeclaredAccessibility != Accessibility.Public && e.ExplicitInterfaceImplementations.Length == 0)
                mods.Add(GetAccessibilityKeyword(e.DeclaredAccessibility));
        }

        var prefix = mods.Count == 0 ? "" : string.Join(" ", mods) + " ";
        var name = e.ExplicitInterfaceImplementations.Length != 0
            ? e.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMemberOptions(SymbolDisplayMemberOptions.IncludeExplicitInterface))
            : e.Name;

        // For explicit impls, ToDisplayString includes containing type; strip it.
        name = StripContainingTypePrefix(name, e.ContainingType);

        return $"{prefix}event {e.Type.ToDisplayString(typeFormat)} {name};";
    }

    private static string RenderProperty(IPropertySymbol p, SymbolDisplayFormat typeFormat, bool inInterface)
    {
        var mods = new List<string>();
        if (!inInterface)
        {
            var acc = p.ExplicitInterfaceImplementations.Length == 0 ? GetAccessibilityKeyword(p.DeclaredAccessibility) : "";
            if (acc.Length != 0) mods.Add(acc);
            if (p.IsStatic) mods.Add("static");
        }
        else
        {
            if (p.IsStatic) mods.Add("static");
            if (p.DeclaredAccessibility != Accessibility.Public && p.ExplicitInterfaceImplementations.Length == 0)
                mods.Add(GetAccessibilityKeyword(p.DeclaredAccessibility));
        }

        var prefix = mods.Count == 0 ? "" : string.Join(" ", mods) + " ";

        string name;
        if (p.IsIndexer)
        {
            var indexerTarget = p.ExplicitInterfaceImplementations.Length != 0
                ? p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMemberOptions(SymbolDisplayMemberOptions.IncludeExplicitInterface))
                : "this";
            indexerTarget = StripContainingTypePrefix(indexerTarget, p.ContainingType);
            name = $"{indexerTarget}[{RenderIndexerParameters(p, typeFormat)}]";
        }
        else
        {
            name = p.ExplicitInterfaceImplementations.Length != 0
                ? p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMemberOptions(SymbolDisplayMemberOptions.IncludeExplicitInterface))
                : p.Name;
            name = StripContainingTypePrefix(name, p.ContainingType);
        }

        var accessors = new List<string>();
        if (p.GetMethod is not null)
            accessors.Add("get;");
        if (p.SetMethod is not null)
            accessors.Add("set;");
        // Roslyn symbols don't expose init accessors directly; treat an init setter as a setter for skeleton purposes.

        return $"{prefix}{p.Type.ToDisplayString(typeFormat)} {name} {{ {string.Join(" ", accessors)} }}";
    }

    private static string RenderMethod(IMethodSymbol m, INamedTypeSymbol containingType, SymbolDisplayFormat typeFormat, SymbolDisplayFormat memberFormat, bool inInterface)
    {
        // Constructors
        if (m.MethodKind == MethodKind.Constructor)
        {
            var acc = inInterface ? "" : GetAccessibilityKeyword(m.DeclaredAccessibility);
            var ctorPrefix = acc.Length == 0 ? "" : acc + " ";
            return $"{ctorPrefix}{containingType.Name}{RenderParameters(m, typeFormat)};";
        }

        // Operators, conversions, normal methods
        var modsList = new List<string>();
        if (!inInterface && m.ExplicitInterfaceImplementations.Length == 0)
        {
            var acc = GetAccessibilityKeyword(m.DeclaredAccessibility);
            if (acc.Length != 0) modsList.Add(acc);
        }
        if (m.IsStatic) modsList.Add("static");
        if (!inInterface)
        {
            if (m.IsAbstract) modsList.Add("abstract");
            else if (m.IsOverride) modsList.Add("override");
            else if (m.IsVirtual) modsList.Add("virtual");
            if (m.IsSealed && m.IsOverride) modsList.Add("sealed");
        }
        else
        {
            // For static abstract interface members, keep the modifiers.
            if (m.IsStatic && m.IsAbstract) modsList.Add("abstract");
            if (m.DeclaredAccessibility != Accessibility.Public && m.ExplicitInterfaceImplementations.Length == 0)
                modsList.Add(GetAccessibilityKeyword(m.DeclaredAccessibility));
        }

        var mods = modsList.Count == 0 ? "" : string.Join(" ", modsList) + " ";

        var name = m.ExplicitInterfaceImplementations.Length != 0
            ? m.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMemberOptions(SymbolDisplayMemberOptions.IncludeExplicitInterface))
            : m.Name;
        name = StripContainingTypePrefix(name, m.ContainingType);

        // Special method names (operators)
        if (m.MethodKind == MethodKind.UserDefinedOperator || m.MethodKind == MethodKind.Conversion)
        {
            return $"{mods}{RenderOperatorOrConversion(m, typeFormat)};";
        }

        var sb = new StringBuilder();
        sb.Append(mods);
        sb.Append(m.ReturnType.ToDisplayString(typeFormat)).Append(' ');
        sb.Append(name);
        sb.Append(RenderTypeParameters(m));
        sb.Append(RenderParameters(m, typeFormat));

        var constraints = RenderTypeParameterConstraints(m, typeFormat);
        if (constraints.Length != 0)
            sb.Append(' ').Append(constraints);
        sb.Append(';');

        return sb.ToString();
    }

    private static string RenderTypeParameters(INamedTypeSymbol t)
    {
        if (t.TypeParameters.Length == 0) return "";
        return "<" + string.Join(", ", t.TypeParameters.Select(tp => tp.Name)) + ">";
    }

    private static string RenderTypeParameters(IMethodSymbol m)
    {
        if (m.TypeParameters.Length == 0) return "";
        return "<" + string.Join(", ", m.TypeParameters.Select(tp => tp.Name)) + ">";
    }

    private static string RenderParameters(IMethodSymbol m, SymbolDisplayFormat typeFormat)
    {
        var ps = m.Parameters;
        if (ps.Length == 0) return "()";

        var parts = new List<string>(ps.Length);
        foreach (var p in ps)
        {
            var sb = new StringBuilder();
            if (p.IsParams) sb.Append("params ");
            sb.Append(p.RefKind switch
            {
                RefKind.In => "in ",
                RefKind.Out => "out ",
                RefKind.Ref => "ref ",
                RefKind.RefReadOnlyParameter => "ref readonly ",
                _ => "",
            });

            sb.Append(p.Type.ToDisplayString(typeFormat)).Append(' ').Append(p.Name);

            if (p.HasExplicitDefaultValue)
                sb.Append(" = ").Append(RenderDefaultValue(p));

            parts.Add(sb.ToString());
        }

        return "(" + string.Join(", ", parts) + ")";
    }

    private static string RenderIndexerParameters(IPropertySymbol p, SymbolDisplayFormat typeFormat)
    {
        if (p.Parameters.Length == 0) return "";
        var parts = new List<string>(p.Parameters.Length);
        foreach (var par in p.Parameters)
        {
            var sb = new StringBuilder();
            sb.Append(par.RefKind switch
            {
                RefKind.In => "in ",
                RefKind.Out => "out ",
                RefKind.Ref => "ref ",
                RefKind.RefReadOnlyParameter => "ref readonly ",
                _ => "",
            });
            sb.Append(par.Type.ToDisplayString(typeFormat)).Append(' ').Append(par.Name);
            if (par.HasExplicitDefaultValue)
                sb.Append(" = ").Append(RenderDefaultValue(par));
            parts.Add(sb.ToString());
        }
        return string.Join(", ", parts);
    }

    private static string RenderTypeParameterConstraints(INamedTypeSymbol t, SymbolDisplayFormat typeFormat)
    {
        if (t.TypeParameters.Length == 0) return "";
        return string.Join(" ", t.TypeParameters.Select(tp => RenderTypeParameterConstraints(tp, typeFormat)).Where(s => s.Length != 0));
    }

    private static string RenderTypeParameterConstraints(IMethodSymbol m, SymbolDisplayFormat typeFormat)
    {
        if (m.TypeParameters.Length == 0) return "";
        return string.Join(" ", m.TypeParameters.Select(tp => RenderTypeParameterConstraints(tp, typeFormat)).Where(s => s.Length != 0));
    }

    private static string RenderTypeParameterConstraints(ITypeParameterSymbol tp, SymbolDisplayFormat typeFormat)
    {
        var parts = new List<string>();
        if (tp.HasNotNullConstraint) parts.Add("notnull");
        if (tp.HasReferenceTypeConstraint) parts.Add(tp.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
        if (tp.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
        if (tp.HasValueTypeConstraint) parts.Add("struct");
        foreach (var ct in tp.ConstraintTypes)
            parts.Add(ct.ToDisplayString(typeFormat));
        if (tp.HasConstructorConstraint) parts.Add("new()");

        if (parts.Count == 0) return "";
        return $"where {tp.Name} : {string.Join(", ", parts)}";
    }

    private static string GetAccessibilityKeyword(Accessibility a) => a switch
    {
        Accessibility.Public => "public",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => "",
    };

    private static string StripContainingTypePrefix(string display, INamedTypeSymbol? containingType)
    {
        if (containingType is null) return display;
        var ct = containingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (display.StartsWith(ct + ".", StringComparison.Ordinal))
            return display[(ct.Length + 1)..];
        return display;
    }

    private static string RenderDefaultValue(IParameterSymbol p)
    {
        // Roslyn uses null for default(T) for many value types; preserve "null" for Nullable<T>.
        if (p.ExplicitDefaultValue is null)
        {
            if (p.Type is INamedTypeSymbol nts &&
                nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                return "null";
            if (p.Type.IsValueType)
                return "default";
            return "null";
        }

        return RenderConstant(p.ExplicitDefaultValue);
    }

    private static string RenderConstant(object? value)
    {
        if (value is null) return "null";
        return value switch
        {
            string s => "@\"" + s.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"",
            char c => "'" + (c == '\'' ? "\\'" : c.ToString()) + "'",
            bool b => b ? "true" : "false",
            float f => f.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f",
            double d => d.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "d",
            decimal m => m.ToString(System.Globalization.CultureInfo.InvariantCulture) + "m",
            sbyte or byte or short or ushort or int or uint or long or ulong =>
                Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture) ?? "0",
            _ => "default",
        };
    }

    private static string RenderOperatorOrConversion(IMethodSymbol m, SymbolDisplayFormat typeFormat)
    {
        // Conversions
        if (m.MethodKind == MethodKind.Conversion)
        {
            var keyword = m.Name switch
            {
                "op_Implicit" => "implicit",
                "op_Explicit" => "explicit",
                _ => "explicit",
            };

            var fromType = m.Parameters.Length == 1 ? m.Parameters[0].Type.ToDisplayString(typeFormat) : "object";
            return $"{keyword} operator {m.ReturnType.ToDisplayString(typeFormat)}({fromType} value)";
        }

        // Operators
        var opToken = m.Name switch
        {
            "op_Addition" => "+",
            "op_Subtraction" => "-",
            "op_Multiply" => "*",
            "op_Division" => "/",
            "op_Modulus" => "%",
            "op_BitwiseAnd" => "&",
            "op_BitwiseOr" => "|",
            "op_ExclusiveOr" => "^",
            "op_LeftShift" => "<<",
            "op_RightShift" => ">>",
            "op_UnsignedRightShift" => ">>>",
            "op_Equality" => "==",
            "op_Inequality" => "!=",
            "op_GreaterThan" => ">",
            "op_LessThan" => "<",
            "op_GreaterThanOrEqual" => ">=",
            "op_LessThanOrEqual" => "<=",
            "op_UnaryNegation" => "-",
            "op_UnaryPlus" => "+",
            "op_LogicalNot" => "!",
            "op_OnesComplement" => "~",
            "op_Increment" => "++",
            "op_Decrement" => "--",
            "op_True" => "true",
            "op_False" => "false",
            _ => m.Name,
        };

        var paramParts = new List<string>(m.Parameters.Length);
        for (var i = 0; i < m.Parameters.Length; i++)
        {
            var p = m.Parameters[i];
            paramParts.Add($"{p.Type.ToDisplayString(typeFormat)} {p.Name}");
        }

        return $"{m.ReturnType.ToDisplayString(typeFormat)} operator {opToken}({string.Join(", ", paramParts)})";
    }

    private sealed class NamedTypeSymbolComparer : IEqualityComparer<INamedTypeSymbol>
    {
        public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y) =>
            SymbolEqualityComparer.Default.Equals(x, y);

        public int GetHashCode(INamedTypeSymbol obj) =>
            SymbolEqualityComparer.Default.GetHashCode(obj);
    }
}
