namespace Avalonia.DBus.SourceGen;

public partial class DBusSourceGenerator
{
    private static string BuildHandlerSource(DBusInterface dBusInterface, string userFacingNamespace, bool isInternal = false)
    {
        var accessModifier = isInternal ? "internal" : "public";
        var interfaceIdentifier = GetHandlerInterfaceIdentifier(dBusInterface);
        var interfaceTypeName = GetGlobalQualifiedTypeName(userFacingNamespace, interfaceIdentifier);
        var dispatcherIdentifier = GetHandlerDispatcherIdentifier(dBusInterface);
        var registrationHelperIdentifier = GetHandlerRegistrationHelperIdentifier(dBusInterface);

        var interfaceNameLiteral = SymbolDisplay.FormatLiteral(dBusInterface.Name!, quote: true);
        var properties = (dBusInterface.Properties ?? [])
            .Where(static p => !string.IsNullOrWhiteSpace(p.Name) && !string.IsNullOrWhiteSpace(p.SafeName))
            .ToArray();
        var methods = (dBusInterface.Methods ?? [])
            .Where(static m => !string.IsNullOrWhiteSpace(m.Name) && !string.IsNullOrWhiteSpace(m.SafeName))
            .ToArray();

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Avalonia.DBus;");
        sb.AppendLine($"using {userFacingNamespace};");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {userFacingNamespace}");
        sb.AppendLine("{");

        sb.AppendLine($"    {accessModifier} interface {interfaceIdentifier}");
        sb.AppendLine("    {");
        foreach (var property in properties)
        {
            var access = GetPropertyAccessors(property.Access);
            if (string.IsNullOrEmpty(access))
                continue;

            var propertyType = property.DBusDotnetType.ToTypeSyntax().ToString();
            var propertyIdentifier = GetPropertyIdentifier(property);
            sb.AppendLine($"        {propertyType} {propertyIdentifier} {{ {access} }}");
        }

        foreach (var method in methods)
        {
            var inArgs = method.Arguments?.Where(static argument => argument.Direction is null or "in").ToArray() ?? [];
            var outArgs = method.Arguments?.Where(static argument => argument.Direction == "out").ToArray() ?? [];
            var returnType = ParseValueTaskReturnType(outArgs).NormalizeWhitespace().ToFullString();
            var parameterList = string.Join(", ", inArgs.Select((argument, index) =>
                $"{argument.DBusDotnetType.ToTypeSyntax()} {GetParameterIdentifier(argument, index)}"));
            sb.AppendLine($"        {returnType} {GetInterfaceMethodIdentifier(method)}({parameterList});");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"namespace {PrivateImplementationNamespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class {dispatcherIdentifier} : IDBusInterfaceCallDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine($"        internal static {dispatcherIdentifier} Instance {{ get; }} = new();");
        sb.AppendLine();
        sb.AppendLine($"        private {dispatcherIdentifier}() {{ }}");
        sb.AppendLine();
        sb.AppendLine("        public async Task<DBusMessage> Handle(IDBusConnection connection, object? target, DBusMessage message)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(connection);");
        sb.AppendLine();
        sb.AppendLine($"            if (target is not {interfaceTypeName} typedTarget)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return message.CreateError(\"org.freedesktop.DBus.Error.UnknownInterface\", \"Target does not implement interface \" + {interfaceNameLiteral} + \".\");");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            switch (message.Member)");
        sb.AppendLine("            {");

        foreach (var method in methods)
        {
            var inArgs = method.Arguments?.Where(static argument => argument.Direction is null or "in").ToArray() ?? [];
            var outArgs = method.Arguments?.Where(static argument => argument.Direction == "out").ToArray() ?? [];
            var methodIdentifier = GetInterfaceMethodIdentifier(method);
            var callArguments = string.Join(", ", inArgs.Select((argument, index) => GetParameterIdentifier(argument, index)));

            sb.AppendLine($"                case {SymbolDisplay.FormatLiteral(method.Name!, quote: true)}:");
            sb.AppendLine("                {");

            // Argument extraction with try/catch → InvalidArgs
            if (inArgs.Length > 0)
            {
                for (var i = 0; i < inArgs.Length; i++)
                {
                    var parameterIdentifier = GetParameterIdentifier(inArgs[i], i);
                    var typeSyntax = inArgs[i].DBusDotnetType.ToTypeSyntax().ToString();
                    sb.AppendLine($"                    {typeSyntax} {parameterIdentifier};");
                }

                sb.AppendLine("                    try");
                sb.AppendLine("                    {");
                for (var i = 0; i < inArgs.Length; i++)
                {
                    var parameterIdentifier = GetParameterIdentifier(inArgs[i], i);
                    var fromDbusExpression = MakeFromDbusValueExpressionString(inArgs[i].DBusDotnetType, $"message.Body[{i}]");
                    sb.AppendLine($"                        {parameterIdentifier} = {fromDbusExpression};");
                }
                sb.AppendLine("                    }");
                sb.AppendLine("                    catch (Exception ex)");
                sb.AppendLine("                    {");
                sb.AppendLine("                        return message.CreateError(\"org.freedesktop.DBus.Error.InvalidArgs\", ex.Message);");
                sb.AppendLine("                    }");
            }

            // User method invocation — exceptions propagate to the handler dispatch loop
            if (outArgs.Length == 0)
            {
                sb.AppendLine($"                    await typedTarget.{methodIdentifier}({callArguments}).ConfigureAwait(false);");
                sb.AppendLine("                    return message.CreateReply();");
            }
            else
            {
                sb.AppendLine($"                    var result = await typedTarget.{methodIdentifier}({callArguments}).ConfigureAwait(false);");

                // Use CreateReplyWithSignature with the compile-time-known D-Bus signature
                // to avoid inference failures on empty arrays of struct types.
                var replySignature = string.Concat(outArgs.Select(static a => a.Type));
                var replySignatureLiteral = SymbolDisplay.FormatLiteral(replySignature, quote: true);

                if (outArgs.Length == 1)
                {
                    var toDbusExpression = MakeToDbusValueExpressionString(outArgs[0].DBusDotnetType, "result");
                    sb.AppendLine($"                    return message.CreateReplyWithSignature({replySignatureLiteral}, {toDbusExpression});");
                }
                else
                {
                    var replyArgs = string.Join(", ", outArgs.Select((argument, index) =>
                        MakeToDbusValueExpressionString(argument.DBusDotnetType, $"result.Item{index + 1}")));
                    sb.AppendLine($"                    return message.CreateReplyWithSignature({replySignatureLiteral}, {replyArgs});");
                }
            }

            sb.AppendLine("                }");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    return message.CreateError(\"org.freedesktop.DBus.Error.UnknownMethod\", \"Unknown method\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static class {registrationHelperIdentifier}");
        sb.AppendLine("    {");
        sb.AppendLine($"        internal const string InterfaceName = {interfaceNameLiteral};");
        sb.AppendLine($"        internal static IDBusInterfaceCallDispatcher CreateHandler() => {dispatcherIdentifier}.Instance;");
        sb.AppendLine();
        EmitWriteIntrospectionXml(sb, dBusInterface);
        sb.AppendLine();
        sb.AppendLine("        private static DBusVariant? TryGetProperty(object target, string propertyName)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(propertyName);");
        sb.AppendLine($"            if (target is not {interfaceTypeName} typedTarget)");
        sb.AppendLine("                return null;");
        sb.AppendLine();
        sb.AppendLine("            switch (propertyName)");
        sb.AppendLine("            {");
        foreach (var property in properties.Where(static p => p.Access is null or "read" or "readwrite"))
        {
            var propertyNameLiteral = SymbolDisplay.FormatLiteral(property.Name!, quote: true);
            var propertyIdentifier = GetPropertyIdentifier(property);
            var toDbusExpression = MakeToDbusValueExpressionString(property.DBusDotnetType, $"typedTarget.{propertyIdentifier}");
            var propertySignatureLiteral = SymbolDisplay.FormatLiteral(property.Type!, quote: true);
            sb.AppendLine($"                case {propertyNameLiteral}:");
            sb.AppendLine($"                    return new DBusVariant({toDbusExpression}, {propertySignatureLiteral});");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    return null;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        internal static bool TrySetProperty(object target, string propertyName, object propertyValue)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(propertyName);");
        sb.AppendLine($"            if (target is not {interfaceTypeName} typedTarget)");
        sb.AppendLine("                return false;");
        sb.AppendLine("            if (propertyValue is not DBusVariant value)");
        sb.AppendLine("                return false;");
        sb.AppendLine();
        sb.AppendLine("            switch (propertyName)");
        sb.AppendLine("            {");
        foreach (var property in properties.Where(static p => p.Access is "write" or "readwrite"))
        {
            var propertyNameLiteral = SymbolDisplay.FormatLiteral(property.Name!, quote: true);
            var propertyIdentifier = GetPropertyIdentifier(property);
            var fromDbusExpression = MakeFromDbusValueExpressionString(property.DBusDotnetType, "value.Value");
            sb.AppendLine($"                case {propertyNameLiteral}:");
            sb.AppendLine($"                    typedTarget.{propertyIdentifier} = {fromDbusExpression};");
            sb.AppendLine("                    return true;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        internal static IReadOnlyDictionary<string, DBusVariant> GetAllProperties(object target)");
        sb.AppendLine("        {");
        sb.AppendLine("            var values = new Dictionary<string, DBusVariant>(StringComparer.Ordinal);");
        sb.AppendLine($"            if (target is not {interfaceTypeName} typedTarget)");
        sb.AppendLine("                return values;");
        foreach (var property in properties.Where(static p => p.Access is null or "read" or "readwrite"))
        {
            var propertyNameLiteral = SymbolDisplay.FormatLiteral(property.Name!, quote: true);
            var propertyIdentifier = GetPropertyIdentifier(property);
            var toDbusExpression = MakeToDbusValueExpressionString(property.DBusDotnetType, $"typedTarget.{propertyIdentifier}");
            var propertySignatureLiteral = SymbolDisplay.FormatLiteral(property.Type!, quote: true);
            sb.AppendLine($"            values[{propertyNameLiteral}] = new DBusVariant({toDbusExpression}, {propertySignatureLiteral});");
        }

        sb.AppendLine("            return values;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetHandlerInterfaceIdentifier(DBusInterface dBusInterface) => $"I{dBusInterface.SafeName}";

    private static string GetHandlerDispatcherIdentifier(DBusInterface dBusInterface) => $"{dBusInterface.SafeName}Dispatcher";

    private static string GetHandlerRegistrationHelperIdentifier(DBusInterface dBusInterface) => $"{dBusInterface.SafeName}HandlerMetadata";

    private static string GetInterfaceMethodIdentifier(DBusMethod method)
        => $"{method.SafeName}Async";

    private static string GetPropertyIdentifier(DBusProperty property)
        => property.SafeName!;

    private static string GetParameterIdentifier(DBusValue argument, int index)
        => argument.Name is not null
            ? SanitizeIdentifier(Camelize(argument.Name.AsSpan()))
            : $"arg{index}";

    private static string GetPropertyAccessors(string? access)
    {
        return access switch
        {
            null or "readwrite" => "get; set;",
            "read" => "get;",
            "write" => "set;",
            _ => string.Empty
        };
    }

    /// <summary>
    /// Emits a static method <c>WriteIntrospectionXml(StringBuilder sb, string indent)</c>
    /// that writes the D-Bus introspection XML for this interface at runtime.
    /// </summary>
    private static void EmitWriteIntrospectionXml(StringBuilder sb, DBusInterface dBusInterface)
    {
        var ifaceName = SymbolDisplay.FormatLiteral(dBusInterface.Name!, quote: true);

        sb.AppendLine("        internal static void WriteIntrospectionXml(System.Text.StringBuilder sb, string indent)");
        sb.AppendLine("        {");
        sb.AppendLine("            var inner = indent + \"  \";");
        sb.AppendLine($"            sb.Append(indent).Append(\"<interface name=\\\"\").Append({ifaceName}).AppendLine(\"\\\">\");");

        foreach (var property in dBusInterface.Properties ?? [])
        {
            if (string.IsNullOrWhiteSpace(property.Name))
                continue;
            var name = SymbolDisplay.FormatLiteral(property.Name!, quote: true);
            var type = SymbolDisplay.FormatLiteral(property.Type!, quote: true);
            var access = SymbolDisplay.FormatLiteral(property.Access ?? "readwrite", quote: true);
            sb.AppendLine($"            sb.Append(inner).Append(\"<property name=\\\"\").Append({name}).Append(\"\\\" type=\\\"\").Append({type}).Append(\"\\\" access=\\\"\").Append({access}).AppendLine(\"\\\"/>\");");
        }

        foreach (var method in dBusInterface.Methods ?? [])
        {
            if (string.IsNullOrWhiteSpace(method.Name))
                continue;
            var args = method.Arguments ?? [];
            var mName = SymbolDisplay.FormatLiteral(method.Name!, quote: true);

            if (args.Length == 0)
            {
                sb.AppendLine($"            sb.Append(inner).Append(\"<method name=\\\"\").Append({mName}).AppendLine(\"\\\"/>\");");
                continue;
            }

            sb.AppendLine($"            sb.Append(inner).Append(\"<method name=\\\"\").Append({mName}).AppendLine(\"\\\">\");");
            foreach (var arg in args)
                EmitArgAppend(sb, arg);
            sb.AppendLine("            sb.Append(inner).AppendLine(\"</method>\");");
        }

        foreach (var signal in dBusInterface.Signals ?? [])
        {
            if (string.IsNullOrWhiteSpace(signal.Name))
                continue;
            var args = signal.Arguments ?? [];
            var sName = SymbolDisplay.FormatLiteral(signal.Name!, quote: true);

            if (args.Length == 0)
            {
                sb.AppendLine($"            sb.Append(inner).Append(\"<signal name=\\\"\").Append({sName}).AppendLine(\"\\\"/>\");");
                continue;
            }

            sb.AppendLine($"            sb.Append(inner).Append(\"<signal name=\\\"\").Append({sName}).AppendLine(\"\\\">\");");
            foreach (var arg in args)
                EmitArgAppend(sb, arg);
            sb.AppendLine("            sb.Append(inner).AppendLine(\"</signal>\");");
        }

        sb.AppendLine("            sb.Append(indent).AppendLine(\"</interface>\");");
        sb.AppendLine("        }");
    }

    private static void EmitArgAppend(StringBuilder sb, DBusArgument arg)
    {
        var type = SymbolDisplay.FormatLiteral(arg.Type!, quote: true);
        // Build: sb.Append(inner).Append("  <arg type=\"").Append(type).Append("\"")...AppendLine("/>");
        sb.Append("            sb.Append(inner).Append(\"  <arg type=\\\"\").Append(").Append(type).Append(").Append(\"\\\"\")");
        if (arg.Name is not null)
        {
            var name = SymbolDisplay.FormatLiteral(arg.Name, quote: true);
            sb.Append(".Append(\" name=\\\"\").Append(").Append(name).Append(").Append(\"\\\"\")");
        }
        if (arg.Direction is not null)
        {
            var dir = SymbolDisplay.FormatLiteral(arg.Direction, quote: true);
            sb.Append(".Append(\" direction=\\\"\").Append(").Append(dir).Append(").Append(\"\\\"\")");
        }
        sb.AppendLine(".AppendLine(\"/>\");");
    }
}
