namespace Avalonia.DBus.SourceGen;

public partial class DBusSourceGenerator
{
    private const string PropertyChangesClass = """
                                                // <auto-generated/>
                                                using System;

                                                #pragma warning disable
                                                #nullable enable
                                                namespace Avalonia.DBus.SourceGen
                                                {
                                                    internal record PropertyChanges<TProperties>(TProperties Properties, string[] Invalidated, string[] Changed)
                                                    {
                                                        public bool HasChanged(string property) => Array.IndexOf(Changed, property) != -1;
                                                        public bool IsInvalidated(string property) => Array.IndexOf(Invalidated, property) != -1;
                                                    }
                                                }

                                                """;
}
