using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;


namespace Avalonia.DBus.SourceGen;

public partial class DBusSourceGenerator
{
    private const string SignalHelperClass = """
                                             // <auto-generated/>
                                             using System;
                                             using System.Threading.Tasks;
                                             
                                             using Avalonia.DBus.AutoGen;
                                             using Avalonia.DBus.Wire;

                                             #pragma warning disable
                                             #nullable enable
                                             namespace Avalonia.DBus.SourceGen
                                             {
                                                 internal static class SignalHelper
                                                 {
                                                    public static ValueTask<IDisposable> WatchSignalAsync(Connection connection, MatchRule rule, Action<Exception?> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                        => connection.AddMatchAsync(rule, static (_, _) => null !, static (Exception? e, object _, object? handlerState) => ((Action<Exception?>)handlerState!).Invoke(e), null, handler, emitOnCapturedContext, flags);

                                                    public static ValueTask<IDisposable> WatchSignalAsync<T>(Connection connection, MatchRule rule, MessageValueReader<T> reader, Action<Exception?, T> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                        => connection.AddMatchAsync(rule, reader, static (Exception? e, T arg, object? handlerState) => ((Action<Exception?, T>)handlerState!).Invoke(e, arg), null, handler, emitOnCapturedContext, flags);

                                                     public static ValueTask<IDisposable> WatchPropertiesChangedAsync<T>(Connection connection, string destination, string path, string @interface, MessageValueReader<PropertyChanges<T>> reader, Action<Exception?, PropertyChanges<T>> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
                                                     {
                                                         MatchRule rule = new()
                                                         {
                                                             Type = MessageType.Signal,
                                                             Sender = destination,
                                                             Path = path,
                                                             Member = "PropertiesChanged",
                                                             Interface = "org.freedesktop.DBus.Properties",
                                                             Arg0 = @interface
                                                         };

                                                         return WatchSignalAsync(connection, rule, reader, handler, emitOnCapturedContext, flags);
                                                     }
                                                 }
                                             }
                                             """;

    private const string PropertyChangesClass = """
                                                // <auto-generated/>
                                                using System;
                                                using Avalonia.DBus.Wire;

                                                #pragma warning disable
                                                #nullable enable
                                                namespace Avalonia.DBus.SourceGen
                                                {
                                                    internal record PropertyChanges<TProperties>(TProperties Properties, string[] Invalidated, string[] Changed)
                                                    {
                                                        public bool HasChanged(string property) => Array.IndexOf(Changed, property) != -1;
                                                        public bool IsInvalidated(string property) => Array.IndexOf(Invalidated, property) != -1;
                                                    }
                                                }

                                                """;

    private const string DBusInterfaceHandlerInterface = """
                                                         // <auto-generated/>
                                                         using System;
                                                         using System.Threading.Tasks;

                                                         using Avalonia.DBus.AutoGen;
                                                         using Avalonia.DBus.Wire;

                                                         #pragma warning disable
                                                         #nullable enable
                                                         namespace Avalonia.DBus.SourceGen
                                                         {
                                                             internal interface IDBusInterfaceHandler
                                                             {
                                                                 PathHandler? PathHandler { get; set; }
                                                             
                                                                 Connection Connection { get; }

                                                                 string InterfaceName { get; }

                                                                 ReadOnlyMemory<byte> IntrospectXml { get; }

                                                                 void ReplyGetProperty(string name, MethodContext context);

                                                                 void ReplyGetAllProperties(MethodContext context);
                                                                 
                                                                 void SetProperty(string name, ref Reader reader);
                                                                 
                                                                 ValueTask ReplyInterfaceRequest(MethodContext context);
                                                             }
                                                         }

                                                         """;

    private const string PathHandlerClass = """
                                            // <auto-generated/>
                                            using System;
                                            using System.Collections.Generic;
                                            using System.IO;
                                            using System.Linq;
                                            using System.Text;
                                            using System.Threading.Tasks;

                                            using Avalonia.DBus.AutoGen;
                                            using Avalonia.DBus.Wire;

                                            #pragma warning disable
                                            #nullable enable
                                            namespace Avalonia.DBus.SourceGen
                                            {
                                                internal class PathHandler : IPathMethodHandler
                                                {
                                                    private readonly ICollection<IDBusInterfaceHandler> _dbusInterfaces;
                                                    private string[] _childNodes;
                                                    private const string ErrorUnknownInterface = "org.freedesktop.DBus.Error.UnknownInterface";
                                                    private const string PropertiesIntrospectXml = "<interface name=\"org.freedesktop.DBus.Properties\">\n  <method name=\"Get\">\n    <arg name=\"interface\" type=\"s\" direction=\"in\"/>\n    <arg name=\"property\" type=\"s\" direction=\"in\"/>\n    <arg name=\"value\" type=\"v\" direction=\"out\"/>\n  </method>\n  <method name=\"Set\">\n    <arg name=\"interface\" type=\"s\" direction=\"in\"/>\n    <arg name=\"property\" type=\"s\" direction=\"in\"/>\n    <arg name=\"value\" type=\"v\" direction=\"in\"/>\n  </method>\n  <method name=\"GetAll\">\n    <arg name=\"interface\" type=\"s\" direction=\"in\"/>\n    <arg name=\"properties\" type=\"a{sv}\" direction=\"out\"/>\n  </method>\n  <signal name=\"PropertiesChanged\">\n    <arg name=\"interface\" type=\"s\"/>\n    <arg name=\"changed_properties\" type=\"a{sv}\"/>\n    <arg name=\"invalidated_properties\" type=\"as\"/>\n  </signal>\n</interface>\n";
                                                    private static readonly ReadOnlyMemory<byte> s_propertiesIntrospectXml = Encoding.UTF8.GetBytes(PropertiesIntrospectXml);
                                                    private static readonly string s_machineId = ResolveMachineId();

                                                    public PathHandler(string path)
                                                    {
                                                        Path = path;
                                                        _dbusInterfaces = new List<IDBusInterfaceHandler>();
                                                        _childNodes = Array.Empty<string>();
                                                    }

                                                    /// <inheritdoc />
                                                    public string Path { get; }

                                                    /// <inheritdoc />
                                                    public bool HandlesChildPaths => false;

                                                    /// <inheritdoc />
                                                    public async ValueTask HandleMethodAsync(MethodContext context)
                                                    {
                                                        switch (context.Request.InterfaceAsString)
                                                        {
                                                            case "org.freedesktop.DBus.Properties":
                                                                switch (context.Request.MemberAsString, context.Request.SignatureAsString)
                                                                {
                                                                    case ("Get", "ss"):
                                                                    {
                                                                        Reply();
                                                                        void Reply()
                                                                        {
                                                                            Reader reader = context.Request.GetBodyReader();
                                                                            string @interface = reader.ReadString();
                                                                            IDBusInterfaceHandler? handler = _dbusInterfaces.FirstOrDefault(x => x.InterfaceName == @interface);
                                                                            if (handler is null)
                                                                            {
                                                                                context.ReplyError(ErrorUnknownInterface, "Unknown interface");
                                                                                return;
                                                                            }
                                                                            string member = reader.ReadString();
                                                                            handler.ReplyGetProperty(member, context);
                                                                        }

                                                                        break;
                                                                    }
                                                                    case ("GetAll", "s"):
                                                                    {
                                                                        Reply();
                                                                        void Reply()
                                                                        {
                                                                            Reader reader = context.Request.GetBodyReader();
                                                                            string @interface = reader.ReadString();
                                                                            IDBusInterfaceHandler? handler = _dbusInterfaces.FirstOrDefault(x => x.InterfaceName == @interface);
                                                                            if (handler is null)
                                                                            {
                                                                                context.ReplyError(ErrorUnknownInterface, "Unknown interface");
                                                                                return;
                                                                            }
                                                                            handler.ReplyGetAllProperties(context);
                                                                        }

                                                                        break;
                                                                    }
                                                                    case ("Set", "ssv"):
                                                                    {
                                                                        Reply();
                                                                        void Reply()
                                                                        {
                                                                            Reader reader = context.Request.GetBodyReader();
                                                                            string @interface = reader.ReadString();
                                                                            IDBusInterfaceHandler? handler = _dbusInterfaces.FirstOrDefault(x => x.InterfaceName == @interface);
                                                                            if (handler is null)
                                                                            {
                                                                                context.ReplyError(ErrorUnknownInterface, "Unknown interface");
                                                                                return;
                                                                            }
                                                                            string member = reader.ReadString();
                                                                            handler.SetProperty(member, ref reader);
                                                                            if (!context.NoReplyExpected)
                                                                            {
                                                                                using MessageWriter writer = context.CreateReplyWriter(null);
                                                                                context.Reply(writer.CreateMessage());
                                                                            }
                                                                        }
                                                                        
                                                                        break;
                                                                    }
                                                                }

                                                                break;
                                                            case "org.freedesktop.DBus.Introspectable":
                                                                ReadOnlyMemory<byte>[] interfaceXmls = _dbusInterfaces.Count > 0
                                                                    ? _dbusInterfaces.Select(static x => x.IntrospectXml).Concat(new[] { s_propertiesIntrospectXml }).ToArray()
                                                                    : Array.Empty<ReadOnlyMemory<byte>>();
                                                                context.ReplyIntrospectXml(interfaceXmls, _childNodes);
                                                                break;
                                                            case "org.freedesktop.DBus.Peer":
                                                                switch (context.Request.MemberAsString)
                                                                {
                                                                    case "Ping":
                                                                        if (!context.NoReplyExpected)
                                                                        {
                                                                            using MessageWriter writer = context.CreateReplyWriter(null);
                                                                            context.Reply(writer.CreateMessage());
                                                                        }

                                                                        break;
                                                                    case "GetMachineId":
                                                                        if (!context.NoReplyExpected)
                                                                        {
                                                                            using MessageWriter writer = context.CreateReplyWriter("s");
                                                                            writer.WriteString(s_machineId);
                                                                            context.Reply(writer.CreateMessage());
                                                                        }

                                                                        break;
                                                                }

                                                                break;
                                                            default:
                                                                IDBusInterfaceHandler? handler = _dbusInterfaces.FirstOrDefault(x => x.InterfaceName == context.Request.InterfaceAsString);
                                                                if (handler is not null)
                                                                    await handler.ReplyInterfaceRequest(context);
                                                                else
                                                                    context.ReplyError(ErrorUnknownInterface, "Unknown interface");
                                                                break;
                                                        }
                                                    }

                                                    /// <inheritdoc />
                                                    public void Add(IDBusInterfaceHandler item)
                                                    {
                                                        item.PathHandler = this;
                                                        _dbusInterfaces.Add(item);
                                                    }

                                                    /// <inheritdoc />
                                                    public bool Contains(IDBusInterfaceHandler item) => _dbusInterfaces.Contains(item);

                                                    /// <inheritdoc />
                                                    public bool Remove(IDBusInterfaceHandler item)
                                                    {
                                                        item.PathHandler = null;
                                                        return _dbusInterfaces.Remove(item);
                                                    }

                                                    /// <inheritdoc />
                                                    public int Count => _dbusInterfaces.Count;

                                                    internal void SetChildNodes(string[] childNodes)
                                                    {
                                                        _childNodes = childNodes ?? Array.Empty<string>();
                                                    }

                                                    private static string ResolveMachineId()
                                                    {
                                                        string[] paths = { "/etc/machine-id", "/var/lib/dbus/machine-id" };
                                                        foreach (string path in paths)
                                                        {
                                                            try
                                                            {
                                                                if (File.Exists(path))
                                                                {
                                                                    string text = File.ReadAllText(path).Trim();
                                                                    if (!string.IsNullOrEmpty(text))
                                                                    {
                                                                        return text;
                                                                    }
                                                                }
                                                            }
                                                            catch
                                                            {
                                                            }
                                                        }

                                                        return "unknown";
                                                    }
                                                }

                                                internal class PathTree : IPathMethodHandler
                                                {
                                                    private const string ErrorUnknownObject = "org.freedesktop.DBus.Error.UnknownObject";
                                                    private readonly object _gate = new();
                                                    private readonly Dictionary<string, PathHandler> _handlers = new(StringComparer.Ordinal);
                                                    private readonly HashSet<string> _activePaths = new(StringComparer.Ordinal);
                                                    private readonly Dictionary<string, PathHandler> _activeHandlers = new(StringComparer.Ordinal);
                                                    private readonly string _rootPath;
                                                    private readonly string[] _rootSegments;

                                                    public PathTree(string rootPath)
                                                    {
                                                        _rootPath = NormalizePath(rootPath);
                                                        _rootSegments = SplitPath(_rootPath);
                                                        Path = _rootPath;
                                                        _handlers[_rootPath] = new PathHandler(_rootPath);
                                                    }

                                                    public string Path { get; }

                                                    public bool HandlesChildPaths => true;

                                                    public PathHandler AddPath(string path)
                                                    {
                                                        path = NormalizePath(path);
                                                        EnsureUnderRoot(path);
                                                        lock (_gate)
                                                        {
                                                            PathHandler handler = EnsureHandler(path);
                                                            if (_activePaths.Add(path))
                                                            {
                                                                RebuildActiveTree();
                                                            }

                                                            return handler;
                                                        }
                                                    }

                                                    public bool RemovePath(string path)
                                                    {
                                                        path = NormalizePath(path);
                                                        EnsureUnderRoot(path);
                                                        lock (_gate)
                                                        {
                                                            if (!_activePaths.Remove(path))
                                                            {
                                                                return false;
                                                            }

                                                            RebuildActiveTree();
                                                            return true;
                                                        }
                                                    }

                                                    public ValueTask HandleMethodAsync(MethodContext context)
                                                    {
                                                        PathHandler? handler;
                                                        lock (_gate)
                                                        {
                                                            if (!_activeHandlers.TryGetValue(context.Request.PathAsString, out handler))
                                                            {
                                                                context.ReplyError(ErrorUnknownObject, "Unknown object path");
                                                                return ValueTask.CompletedTask;
                                                            }
                                                        }

                                                        return handler.HandleMethodAsync(context);
                                                    }

                                                    private PathHandler EnsureHandler(string path)
                                                    {
                                                        if (!_handlers.TryGetValue(path, out PathHandler? handler))
                                                        {
                                                            handler = new PathHandler(path);
                                                            _handlers[path] = handler;
                                                        }

                                                        return handler;
                                                    }

                                                    private void RebuildActiveTree()
                                                    {
                                                        _activeHandlers.Clear();

                                                        var activeNodes = new HashSet<string>(StringComparer.Ordinal);
                                                        var children = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);

                                                        foreach (string path in _activePaths)
                                                        {
                                                            AddActivePath(path, activeNodes, children);
                                                        }

                                                        foreach (var pair in _handlers)
                                                        {
                                                            if (children.TryGetValue(pair.Key, out HashSet<string>? childNames))
                                                            {
                                                                string[] sortedChildren = childNames.OrderBy(static x => x, StringComparer.Ordinal).ToArray();
                                                                pair.Value.SetChildNodes(sortedChildren);
                                                            }
                                                            else
                                                            {
                                                                pair.Value.SetChildNodes(Array.Empty<string>());
                                                            }
                                                        }

                                                        foreach (string path in activeNodes)
                                                        {
                                                            if (_handlers.TryGetValue(path, out PathHandler? handler))
                                                            {
                                                                _activeHandlers[path] = handler;
                                                            }
                                                        }
                                                    }

                                                    private void AddActivePath(string path, HashSet<string> activeNodes, Dictionary<string, HashSet<string>> children)
                                                    {
                                                        EnsureHandler(path);

                                                        string[] segments = SplitPath(path);
                                                        string current = _rootPath;
                                                        activeNodes.Add(current);

                                                        for (int i = _rootSegments.Length; i < segments.Length; i++)
                                                        {
                                                            string child = segments[i];
                                                            string next = current == "/" ? "/" + child : current + "/" + child;
                                                            EnsureHandler(next);
                                                            activeNodes.Add(next);

                                                            if (!children.TryGetValue(current, out HashSet<string>? childSet))
                                                            {
                                                                childSet = new HashSet<string>(StringComparer.Ordinal);
                                                                children[current] = childSet;
                                                            }
                                                            childSet.Add(child);

                                                            current = next;
                                                        }
                                                    }

                                                    private static string NormalizePath(string path)
                                                    {
                                                        if (string.IsNullOrWhiteSpace(path))
                                                        {
                                                            throw new ArgumentException("Path must be provided.", nameof(path));
                                                        }

                                                        if (!path.StartsWith("/", StringComparison.Ordinal))
                                                        {
                                                            throw new ArgumentException("Path must start with '/'.", nameof(path));
                                                        }

                                                        if (path.Length > 1 && path.EndsWith("/", StringComparison.Ordinal))
                                                        {
                                                            path = path.TrimEnd('/');
                                                        }

                                                        return path;
                                                    }

                                                    private static string[] SplitPath(string path)
                                                    {
                                                        if (path == "/")
                                                        {
                                                            return Array.Empty<string>();
                                                        }

                                                        return path.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
                                                    }

                                                    private void EnsureUnderRoot(string path)
                                                    {
                                                        if (_rootPath == "/")
                                                        {
                                                            return;
                                                        }

                                                        if (string.Equals(path, _rootPath, StringComparison.Ordinal))
                                                        {
                                                            return;
                                                        }

                                                        if (!path.StartsWith(_rootPath, StringComparison.Ordinal) || path.Length <= _rootPath.Length || path[_rootPath.Length] != '/')
                                                        {
                                                            throw new ArgumentException("Path must be under the root path.", nameof(path));
                                                        }
                                                    }
                                                }
                                            }
                                            """;

    private static MethodDeclarationSyntax MakeWriteNullableStringMethod() =>
        MethodDeclaration(
                PredefinedType(Token(SyntaxKind.VoidKeyword)),
                "WriteNullableString")
            .AddModifiers(
                Token(SyntaxKind.PublicKeyword),
                Token(SyntaxKind.StaticKeyword))
            .AddParameterListParameters(
                Parameter(
                        Identifier("writer"))
                    .WithType(
                        IdentifierName("MessageWriter"))
                    .AddModifiers(
                        Token(SyntaxKind.ThisKeyword),
                        Token(SyntaxKind.RefKeyword)),
                Parameter(
                        Identifier("value"))
                    .WithType(
                        NullableType(
                            PredefinedType(Token(SyntaxKind.StringKeyword)))))
            .WithExpressionBody(
                ArrowExpressionClause(
                    InvocationExpression(
                            MakeMemberAccessExpression("writer", "WriteString"))
                        .AddArgumentListArguments(
                            Argument(
                                BinaryExpression(
                                    SyntaxKind.CoalesceExpression,
                                    IdentifierName("value"),
                                    MakeMemberAccessExpression("string", "Empty"))))))
            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));

    private static MethodDeclarationSyntax MakeWriteObjectPathSafeMethod() =>
        MethodDeclaration(
                PredefinedType(Token(SyntaxKind.VoidKeyword)),
                "WriteObjectPathSafe")
            .AddModifiers(
                Token(SyntaxKind.PublicKeyword),
                Token(SyntaxKind.StaticKeyword))
            .AddParameterListParameters(
                Parameter(
                        Identifier("writer"))
                    .WithType(
                        IdentifierName("MessageWriter"))
                    .AddModifiers(
                        Token(SyntaxKind.ThisKeyword),
                        Token(SyntaxKind.RefKeyword)),
                Parameter(
                        Identifier("value"))
                    .WithType(
                        IdentifierName("ObjectPath")))
            .WithExpressionBody(
                ArrowExpressionClause(
                    InvocationExpression(
                            MakeMemberAccessExpression("writer", "WriteObjectPath"))
                        .AddArgumentListArguments(
                            Argument(
                                InvocationExpression(
                                    MakeMemberAccessExpression("value", "ToString"))))))
            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
}
