namespace Avalonia.DBus.SourceGen;

public partial class DBusSourceGenerator
{
    private const string PropertyChangesClass = """
                                                // <auto-generated/>
                                                using System;

                                                #pragma warning disable
                                                #nullable enable
                                                namespace Avalonia.DBus.SourceGen
                                                {
                                                    internal record PropertyChanges<TProperties>(TProperties Properties, string[] Invalidated, string[] Changed)
                                                    {
                                                        public bool HasChanged(string property) => Array.IndexOf(Changed, property) != -1;
                                                        public bool IsInvalidated(string property) => Array.IndexOf(Invalidated, property) != -1;
                                                    }
                                                }

                                                """;

    private const string DBusObjectTreeClass = """
                                               // <auto-generated/>
                                               using System;
                                               using System.Collections.Generic;
                                               using System.Linq;

                                               #pragma warning disable
                                               #nullable enable
                                               namespace Avalonia.DBus
                                               {
                                                   /// <summary>
                                                   /// Utility for maintaining a dynamic D-Bus object subtree and registering its active objects.
                                                   /// Generated by Avalonia.DBus.SourceGen to keep source-gen helpers out of the runtime assembly.
                                                   /// </summary>
                                                   public sealed class DBusObjectTree
                                                   {
                                                       private readonly object _gate = new object();
                                                       private readonly Dictionary<string, DBusObject> _objects = new Dictionary<string, DBusObject>(StringComparer.Ordinal);
                                                       private readonly HashSet<string> _activePaths = new HashSet<string>(StringComparer.Ordinal);
                                                       private readonly Dictionary<string, DBusObject> _activeObjects = new Dictionary<string, DBusObject>(StringComparer.Ordinal);
                                                       private readonly string _rootPath;
                                                       private readonly string[] _rootSegments;

                                                       public DBusObjectTree(string rootPath)
                                                       {
                                                           _rootPath = NormalizePath(rootPath);
                                                           _rootSegments = SplitPath(_rootPath);
                                                           Path = _rootPath;
                                                           _objects[_rootPath] = new DBusObject(_rootPath);
                                                       }

                                                       public string Path { get; }

                                                       public DBusObject AddPath(string path)
                                                       {
                                                           path = NormalizePath(path);
                                                           EnsureUnderRoot(path);
                                                           lock (_gate)
                                                           {
                                                               var obj = EnsureObject(path);
                                                               if (_activePaths.Add(path))
                                                               {
                                                                   RebuildActiveTree();
                                                               }

                                                               return obj;
                                                           }
                                                       }

                                                       public bool RemovePath(string path)
                                                       {
                                                           path = NormalizePath(path);
                                                           EnsureUnderRoot(path);
                                                           lock (_gate)
                                                           {
                                                               if (!_activePaths.Remove(path))
                                                                   return false;

                                                               RebuildActiveTree();
                                                               return true;
                                                           }
                                                       }

                                                       public IDisposable Register(DBusConnection connection)
                                                       {
                                                           var registrations = new List<IDisposable>();
                                                           lock (_gate)
                                                           {
                                                               registrations.AddRange(_activeObjects.Values.Select(handler => connection.RegisterObject(handler)));
                                                           }

                                                           return new CompositeDisposable(registrations);
                                                       }

                                                       private DBusObject EnsureObject(string path)
                                                       {
                                                           if (_objects.TryGetValue(path, out var obj)) return obj;
                                                           obj = new DBusObject(path);
                                                           _objects[path] = obj;
                                                           return obj;
                                                       }

                                                       private void RebuildActiveTree()
                                                       {
                                                           _activeObjects.Clear();

                                                           var activeNodes = new HashSet<string>(StringComparer.Ordinal);
                                                           var children = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);

                                                           foreach (var path in _activePaths) AddActivePath(path, activeNodes, children);

                                                           foreach (var pair in _objects)
                                                           {
                                                               if (children.TryGetValue(pair.Key, out var childNames))
                                                               {
                                                                   var sortedChildren = childNames.OrderBy(static x => x, StringComparer.Ordinal).ToArray();
                                                                   pair.Value.SetChildNodes(sortedChildren);
                                                               }
                                                               else
                                                                   pair.Value.SetChildNodes(Array.Empty<string>());
                                                           }

                                                           foreach (var path in activeNodes)
                                                           {
                                                               if (_objects.TryGetValue(path, out var obj)) _activeObjects[path] = obj;
                                                           }
                                                       }

                                                       private void AddActivePath(string path, HashSet<string> activeNodes, Dictionary<string, HashSet<string>> children)
                                                       {
                                                           EnsureObject(path);

                                                           var segments = SplitPath(path);
                                                           var current = _rootPath;
                                                           activeNodes.Add(current);

                                                           for (var i = _rootSegments.Length; i < segments.Length; i++)
                                                           {
                                                               var child = segments[i];
                                                               var next = current == "/" ? "/" + child : current + "/" + child;
                                                               EnsureObject(next);
                                                               activeNodes.Add(next);

                                                               if (!children.TryGetValue(current, out var childSet))
                                                               {
                                                                   childSet = new HashSet<string>(StringComparer.Ordinal);
                                                                   children[current] = childSet;
                                                               }
                                                               childSet.Add(child);

                                                               current = next;
                                                           }
                                                       }

                                                       private static string NormalizePath(string path)
                                                       {
                                                           if (string.IsNullOrWhiteSpace(path))
                                                               throw new ArgumentException("Path must be provided.", nameof(path));

                                                           if (!path.StartsWith('/'))
                                                               throw new ArgumentException("Path must start with '/'.", nameof(path));

                                                           if (path.Length > 1 && path.EndsWith('/')) path = path.TrimEnd('/');

                                                           return path;
                                                       }

                                                       private static string[] SplitPath(string path)
                                                       {
                                                           return path == "/" ? Array.Empty<string>() : path.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
                                                       }

                                                       private void EnsureUnderRoot(string path)
                                                       {
                                                           if (_rootPath == "/")
                                                               return;

                                                           if (string.Equals(path, _rootPath, StringComparison.Ordinal))
                                                               return;

                                                           if (!path.StartsWith(_rootPath, StringComparison.Ordinal) || path.Length <= _rootPath.Length || path[_rootPath.Length] != '/')
                                                               throw new ArgumentException("Path must be under the root path.", nameof(path));
                                                       }

                                                       private sealed class CompositeDisposable : IDisposable
                                                       {
                                                           private readonly IReadOnlyList<IDisposable> _items;

                                                           public CompositeDisposable(IReadOnlyList<IDisposable> items) => _items = items;

                                                           public void Dispose()
                                                           {
                                                               foreach (var item in _items)
                                                                   item.Dispose();
                                                           }
                                                       }
                                                   }
                                               }

                                               """;

    private const string DBusObjectClass = """
                                           // <auto-generated/>
                                           using System;
                                           using System.Collections;
                                           using System.Collections.Generic;
                                           using System.Linq;
                                           using System.Text;
                                           using System.Threading.Tasks;

                                           #pragma warning disable
                                           #nullable enable
                                           namespace Avalonia.DBus
                                           {
                                               /// <summary>
                                               /// Helper implementation of <see cref="IDBusObject"/> for service-side method dispatch and introspection.
                                               /// Generated by Avalonia.DBus.SourceGen to keep service-side helpers out of the runtime assembly.
                                               /// </summary>
                                               public sealed class DBusObject : ICollection<IDBusInterfaceHandler>, IDBusObject
                                               {
                                                   private const string ErrorUnknownInterface = "org.freedesktop.DBus.Error.UnknownInterface";
                                                   private static readonly DBusVariant MissingProperty = new DBusVariant(string.Empty);

                                                   private readonly DBusBuiltIns _builtIns;
                                                   private readonly List<IDBusInterfaceHandler> _interfaces = new List<IDBusInterfaceHandler>();
                                                   private string[] _childNodes = Array.Empty<string>();

                                                   public DBusObject(string path, DBusBuiltIns? builtIns = null)
                                                   {
                                                       if (string.IsNullOrWhiteSpace(path))
                                                           throw new ArgumentException("Path must be provided.", nameof(path));

                                                       Path = new DBusObjectPath(path);
                                                       _builtIns = builtIns ?? new DBusBuiltIns();
                                                   }

                                                   public DBusObject(DBusObjectPath path, DBusBuiltIns? builtIns = null)
                                                   {
                                                       Path = path;
                                                       _builtIns = builtIns ?? new DBusBuiltIns();
                                                   }

                                                   public DBusBuiltIns BuiltIns => _builtIns;

                                                   public DBusObjectPath Path { get; }

                                                   public string IntrospectXml => BuildIntrospectionXml();

                                                   public bool HasInterface(string name)
                                                   {
                                                       if (string.IsNullOrEmpty(name))
                                                           return false;

                                                       return FindInterface(name) != null;
                                                   }

                                                   public bool TryGetProperty(string iface, string name, out DBusVariant value)
                                                   {
                                                       var handler = FindInterface(iface);
                                                       if (handler != null)
                                                           return handler.TryGetProperty(name, out value);

                                                       value = MissingProperty;
                                                       return false;
                                                   }

                                                   public bool TrySetProperty(string iface, string name, DBusVariant value)
                                                   {
                                                       var handler = FindInterface(iface);
                                                       return handler != null && handler.TrySetProperty(name, value);
                                                   }

                                                   public Dictionary<string, DBusVariant> GetAllProperties(string iface)
                                                   {
                                                       var handler = FindInterface(iface);
                                                       if (handler == null)
                                                           throw new InvalidOperationException("Unknown interface.");

                                                       return handler.GetAllProperties();
                                                   }

                                                   public Task<DBusMessage> HandleMethodAsync(DBusMessage request)
                                                   {
                                                       var iface = request.Interface;
                                                       if (string.IsNullOrEmpty(iface))
                                                           return Task.FromResult(request.CreateError(ErrorUnknownInterface, "Unknown interface"));

                                                       var handler = FindInterface(iface);
                                                       if (handler == null)
                                                           return Task.FromResult(request.CreateError(ErrorUnknownInterface, "Unknown interface"));

                                                       return handler.HandleMethodAsync(request);
                                                   }

                                                   public void Add(IDBusInterfaceHandler item)
                                                   {
                                                       item.Path = Path;
                                                       _interfaces.Add(item);
                                                   }

                                                   public bool Contains(IDBusInterfaceHandler item) => _interfaces.Contains(item);

                                                   public bool Remove(IDBusInterfaceHandler item)
                                                   {
                                                       item.Path = null;
                                                       return _interfaces.Remove(item);
                                                   }

                                                   public void Clear()
                                                   {
                                                       foreach (var item in _interfaces)
                                                           item.Path = null;

                                                       _interfaces.Clear();
                                                   }

                                                   public int Count => _interfaces.Count;

                                                   public bool IsReadOnly => false;

                                                   public void CopyTo(IDBusInterfaceHandler[] array, int arrayIndex) => _interfaces.CopyTo(array, arrayIndex);

                                                   public IEnumerator<IDBusInterfaceHandler> GetEnumerator() => _interfaces.GetEnumerator();

                                                   IEnumerator IEnumerable.GetEnumerator() => _interfaces.GetEnumerator();

                                                   public void SetChildNodes(string[] childNodes)
                                                   {
                                                       _childNodes = childNodes ?? Array.Empty<string>();
                                                   }

                                                   private IDBusInterfaceHandler? FindInterface(string iface)
                                                   {
                                                       if (string.IsNullOrEmpty(iface))
                                                           return null;

                                                       return _interfaces.FirstOrDefault(handler => string.Equals(handler.InterfaceName, iface, StringComparison.Ordinal));
                                                   }

                                                   private string BuildIntrospectionXml()
                                                   {
                                                       var sb = new StringBuilder();
                                                       sb.Append("<node>");

                                                       foreach (var handler in _interfaces)
                                                           sb.Append(handler.IntrospectXml);

                                                       if (_interfaces.Count > 0 && _builtIns.EnablePropertiesInterface)
                                                           sb.Append(DBusBuiltIns.PropertiesIntrospectXml);

                                                       if (_builtIns.EnableIntrospectableInterface)
                                                           sb.Append(DBusBuiltIns.IntrospectableIntrospectXml);

                                                       if (_builtIns.EnablePeerInterface)
                                                           sb.Append(DBusBuiltIns.PeerIntrospectXml);

                                                       foreach (var child in _childNodes)
                                                       {
                                                           sb.Append("<node name='");
                                                           sb.Append(child);
                                                           sb.Append("'/>");
                                                       }

                                                       sb.Append("</node>");
                                                       return sb.ToString();
                                                   }
                                               }
                                           }

                                           """;

    private const string IDBusObjectClass = """
                                            // <auto-generated/>
                                            using System.Collections.Generic;
                                            using System.Threading.Tasks;

                                            #pragma warning disable
                                            #nullable enable
                                            namespace Avalonia.DBus
                                            {
                                                public interface IDBusObject
                                                {
                                                    DBusObjectPath Path { get; }

                                                    string IntrospectXml { get; }

                                                    bool HasInterface(string name);

                                                    bool TryGetProperty(string iface, string name, out DBusVariant value);

                                                    bool TrySetProperty(string iface, string name, DBusVariant value);

                                                    Dictionary<string, DBusVariant> GetAllProperties(string iface);

                                                    Task<DBusMessage> HandleMethodAsync(DBusMessage request);
                                                }
                                            }

                                            """;

    private const string DBusBuiltInsClass = """
                                             // <auto-generated/>
                                             using System;
                                             using System.Collections.Generic;
                                             using System.IO;

                                             #pragma warning disable
                                             #nullable enable
                                             namespace Avalonia.DBus
                                             {
                                                 public sealed class DBusBuiltIns
                                                 {
                                                     public const string PeerInterfaceName = "org.freedesktop.DBus.Peer";
                                                     public const string PropertiesInterfaceName = "org.freedesktop.DBus.Properties";
                                                     public const string IntrospectableInterfaceName = "org.freedesktop.DBus.Introspectable";

                                                     public const string PropertiesIntrospectXml = "<interface name=\"org.freedesktop.DBus.Properties\">\n  <method name=\"Get\">\n    <arg name=\"interface\" type=\"s\" direction=\"in\"/>\n    <arg name=\"property\" type=\"s\" direction=\"in\"/>\n    <arg name=\"value\" type=\"v\" direction=\"out\"/>\n  </method>\n  <method name=\"Set\">\n    <arg name=\"interface\" type=\"s\" direction=\"in\"/>\n    <arg name=\"property\" type=\"s\" direction=\"in\"/>\n    <arg name=\"value\" type=\"v\" direction=\"in\"/>\n  </method>\n  <method name=\"GetAll\">\n    <arg name=\"interface\" type=\"s\" direction=\"in\"/>\n    <arg name=\"properties\" type=\"a{sv}\" direction=\"out\"/>\n  </method>\n  <signal name=\"PropertiesChanged\">\n    <arg name=\"interface\" type=\"s\"/>\n    <arg name=\"changed_properties\" type=\"a{sv}\"/>\n    <arg name=\"invalidated_properties\" type=\"as\"/>\n  </signal>\n</interface>\n";
                                                     public const string IntrospectableIntrospectXml = "<interface name=\"org.freedesktop.DBus.Introspectable\">\n  <method name=\"Introspect\">\n    <arg name=\"xml_data\" type=\"s\" direction=\"out\"/>\n  </method>\n</interface>\n";
                                                     public const string PeerIntrospectXml = "<interface name=\"org.freedesktop.DBus.Peer\">\n  <method name=\"Ping\" />\n  <method name=\"GetMachineId\">\n    <arg name=\"machine_uuid\" type=\"s\" direction=\"out\" />\n  </method>\n</interface>\n";

                                                     private const string ErrorUnknownMethod = "org.freedesktop.DBus.Error.UnknownMethod";
                                                     private const string ErrorUnknownInterface = "org.freedesktop.DBus.Error.UnknownInterface";
                                                     private const string ErrorUnknownProperty = "org.freedesktop.DBus.Error.UnknownProperty";

                                                     private string? _machineId;

                                                     public bool EnablePeerInterface { get; set; } = true;
                                                     public bool EnablePropertiesInterface { get; set; } = true;
                                                     public bool EnableIntrospectableInterface { get; set; } = true;

                                                     public DBusMessage? TryHandlePeer(DBusMessage request)
                                                     {
                                                         if (!EnablePeerInterface)
                                                             return null;

                                                         if (request.Type != DBusMessageType.MethodCall)
                                                             return null;

                                                         if (!string.Equals(request.Interface, PeerInterfaceName, StringComparison.Ordinal))
                                                             return null;

                                                         return request.Member switch
                                                         {
                                                             "Ping" => request.CreateReply(),
                                                             "GetMachineId" => request.CreateReply(GetMachineId()),
                                                             _ => request.CreateError(ErrorUnknownMethod, "Unknown method")
                                                         };
                                                     }

                                                     public DBusMessage? TryHandleProperties(DBusMessage request, IDBusObject obj)
                                                     {
                                                         if (!EnablePropertiesInterface)
                                                             return null;

                                                         if (request.Type != DBusMessageType.MethodCall)
                                                             return null;

                                                         if (!string.Equals(request.Interface, PropertiesInterfaceName, StringComparison.Ordinal))
                                                             return null;

                                                         switch (request.Member)
                                                         {
                                                             case "Get":
                                                                 {
                                                                     if (request.Body.Count < 2 || request.Body[0] is not string iface || request.Body[1] is not string name)
                                                                     {
                                                                         return request.CreateError(ErrorUnknownMethod, "Invalid Get arguments.");
                                                                     }

                                                                     if (!obj.HasInterface(iface))
                                                                     {
                                                                         return request.CreateError(ErrorUnknownInterface, "Unknown interface");
                                                                     }

                                                                     if (!obj.TryGetProperty(iface, name, out var value))
                                                                     {
                                                                         return request.CreateError(ErrorUnknownProperty, "Unknown property");
                                                                     }

                                                                     return request.CreateReply(value);
                                                                 }
                                                             case "GetAll":
                                                                 {
                                                                     if (request.Body.Count < 1 || request.Body[0] is not string iface)
                                                                     {
                                                                         return request.CreateError(ErrorUnknownMethod, "Invalid GetAll arguments.");
                                                                     }

                                                                     if (!obj.HasInterface(iface))
                                                                     {
                                                                         return request.CreateError(ErrorUnknownInterface, "Unknown interface");
                                                                     }

                                                                     var props = obj.GetAllProperties(iface);
                                                                     return request.CreateReply(props);
                                                                 }
                                                             case "Set":
                                                                 {
                                                                     if (request.Body.Count < 3 || request.Body[0] is not string iface || request.Body[1] is not string name || request.Body[2] is not DBusVariant value)
                                                                         return request.CreateError(ErrorUnknownMethod, "Invalid Set arguments.");

                                                                     if (!obj.HasInterface(iface))
                                                                         return request.CreateError(ErrorUnknownInterface, "Unknown interface");

                                                                     if (!obj.TrySetProperty(iface, name, value))
                                                                         return request.CreateError(ErrorUnknownProperty, "Unknown property");

                                                                     return request.CreateReply();
                                                                 }
                                                             default:
                                                                 return request.CreateError(ErrorUnknownMethod, "Unknown method");
                                                         }
                                                     }

                                                     public DBusMessage? TryHandleIntrospectable(DBusMessage request, IDBusObject obj)
                                                     {
                                                         if (!EnableIntrospectableInterface)
                                                             return null;

                                                         if (request.Type != DBusMessageType.MethodCall)
                                                             return null;

                                                         if (!string.Equals(request.Interface, IntrospectableInterfaceName, StringComparison.Ordinal))
                                                             return null;

                                                         return request.Member switch
                                                         {
                                                             "Introspect" => request.CreateReply(obj.IntrospectXml),
                                                             _ => request.CreateError(ErrorUnknownMethod, "Unknown method")
                                                         };
                                                     }

                                                     private string GetMachineId()
                                                     {
                                                         if (!string.IsNullOrEmpty(_machineId))
                                                             return _machineId!;

                                                         string[] paths = new[] { "/etc/machine-id", "/var/lib/dbus/machine-id" };
                                                         foreach (var path in paths)
                                                         {
                                                             try
                                                             {
                                                                 if (!File.Exists(path))
                                                                     continue;
                                                                 var text = File.ReadAllText(path).Trim();
                                                                 if (!string.IsNullOrEmpty(text))
                                                                 {
                                                                     _machineId = text;
                                                                     return text;
                                                                 }
                                                             }
                                                             catch
                                                             {
                                                                 // ignored
                                                             }
                                                         }

                                                         _machineId = "unknown";
                                                         return _machineId;
                                                     }
                                                 }
                                             }

                                             """;

    private const string DBusConnectionObjectExtensionsClass = """
                                                               // <auto-generated/>
                                                               using System;
                                                               using System.Collections.Generic;
                                                               using System.Threading;
                                                               using System.Threading.Tasks;

                                                               #pragma warning disable
                                                               #nullable enable
                                                               namespace Avalonia.DBus
                                                               {
                                                                   public static class DBusConnectionObjectExtensions
                                                                   {
                                                                       public static IDisposable RegisterObject(
                                                                           this DBusConnection connection,
                                                                           DBusObject obj,
                                                                           SynchronizationContext? synchronizationContext = null,
                                                                           DBusBuiltIns? builtIns = null)
                                                                       {
                                                                           if (connection == null)
                                                                               throw new ArgumentNullException(nameof(connection));
                                                                           if (obj == null)
                                                                               throw new ArgumentNullException(nameof(obj));

                                                                           var bi = builtIns ?? obj.BuiltIns ?? new DBusBuiltIns();

                                                                           // Avoid duplicate registrations (built-ins vs user-provided handlers).
                                                                           var ifaces = new HashSet<string>(StringComparer.Ordinal);
                                                                           foreach (var h in obj)
                                                                           {
                                                                               if (h != null && !string.IsNullOrEmpty(h.InterfaceName))
                                                                                   ifaces.Add(h.InterfaceName);
                                                                           }

                                                                           var registrations = new List<IDisposable>();

                                                                           foreach (var handler in obj)
                                                                           {
                                                                               if (handler == null || string.IsNullOrEmpty(handler.InterfaceName))
                                                                                   continue;

                                                                               registrations.Add(
                                                                                   connection.RegisterObject(
                                                                                       obj.Path,
                                                                                       handler.InterfaceName,
                                                                                       handler.HandleMethodAsync,
                                                                                       synchronizationContext));
                                                                           }

                                                                           if (bi.EnablePeerInterface && !ifaces.Contains(DBusBuiltIns.PeerInterfaceName))
                                                                           {
                                                                               registrations.Add(
                                                                                   connection.RegisterObject(
                                                                                       obj.Path,
                                                                                       DBusBuiltIns.PeerInterfaceName,
                                                                                       msg => Task.FromResult(bi.TryHandlePeer(msg) ?? msg.CreateError("org.freedesktop.DBus.Error.Failed", "Peer handler returned null reply.")),
                                                                                       synchronizationContext));
                                                                           }

                                                                           if (bi.EnablePropertiesInterface && !ifaces.Contains(DBusBuiltIns.PropertiesInterfaceName))
                                                                           {
                                                                               registrations.Add(
                                                                                   connection.RegisterObject(
                                                                                       obj.Path,
                                                                                       DBusBuiltIns.PropertiesInterfaceName,
                                                                                       msg => Task.FromResult(bi.TryHandleProperties(msg, obj) ?? msg.CreateError("org.freedesktop.DBus.Error.Failed", "Properties handler returned null reply.")),
                                                                                       synchronizationContext));
                                                                           }

                                                                           if (bi.EnableIntrospectableInterface && !ifaces.Contains(DBusBuiltIns.IntrospectableInterfaceName))
                                                                           {
                                                                               registrations.Add(
                                                                                   connection.RegisterObject(
                                                                                       obj.Path,
                                                                                       DBusBuiltIns.IntrospectableInterfaceName,
                                                                                       msg => Task.FromResult(bi.TryHandleIntrospectable(msg, obj) ?? msg.CreateError("org.freedesktop.DBus.Error.Failed", "Introspectable handler returned null reply.")),
                                                                                       synchronizationContext));
                                                                           }

                                                                           return new CompositeDisposable(registrations);
                                                                       }

                                                                       private sealed class CompositeDisposable : IDisposable
                                                                       {
                                                                           private readonly IReadOnlyList<IDisposable> _items;

                                                                           public CompositeDisposable(IReadOnlyList<IDisposable> items)
                                                                           {
                                                                               _items = items;
                                                                           }

                                                                           public void Dispose()
                                                                           {
                                                                               foreach (var item in _items)
                                                                                   item.Dispose();
                                                                           }
                                                                       }
                                                                   }
                                                               }

                                                               """;
}
