using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Avalonia.DBus.SourceGen;

public partial class DBusSourceGenerator
{
    private static string BuildServiceSource(DBusInterface dBusInterface)
    {
        var interfaceIdentifier = GetServiceInterfaceIdentifier(dBusInterface);
        var dispatcherIdentifier = GetServiceDispatcherIdentifier(dBusInterface);
        var exportHelperIdentifier = GetServiceExportHelperIdentifier(dBusInterface);
        var moduleInitializerIdentifier = GetServiceModuleInitializerIdentifier(dBusInterface);

        var interfaceNameLiteral = SymbolDisplay.FormatLiteral(dBusInterface.Name!, quote: true);
        var properties = dBusInterface.Properties ?? Array.Empty<DBusProperty>();
        var methods = dBusInterface.Methods ?? Array.Empty<DBusMethod>();

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Avalonia.DBus;");
        sb.AppendLine();
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Avalonia.DBus.SourceGen");
        sb.AppendLine("{");

        sb.AppendLine($"    internal interface {interfaceIdentifier}");
        sb.AppendLine("    {");
        foreach (var property in properties)
        {
            var access = GetPropertyAccessors(property.Access);
            if (string.IsNullOrEmpty(access))
                continue;

            var propertyType = property.DBusDotnetType.ToTypeSyntax().ToString();
            var propertyIdentifier = GetPropertyIdentifier(property);
            sb.AppendLine($"        {propertyType} {propertyIdentifier} {{ {access} }}");
        }

        foreach (var method in methods)
        {
            var inArgs = method.Arguments?.Where(static argument => argument.Direction is null or "in").ToArray() ?? Array.Empty<DBusArgument>();
            var outArgs = method.Arguments?.Where(static argument => argument.Direction == "out").ToArray() ?? Array.Empty<DBusArgument>();
            var returnType = ParseValueTaskReturnType(outArgs).NormalizeWhitespace().ToFullString();
            var parameterList = string.Join(", ", inArgs.Select((argument, index) =>
                $"{argument.DBusDotnetType.ToTypeSyntax()} {GetParameterIdentifier(argument, index)}"));
            sb.AppendLine($"        {returnType} {GetInterfaceMethodIdentifier(method)}({parameterList});");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal sealed class {dispatcherIdentifier}");
        sb.AppendLine("    {");
        sb.AppendLine("        public async Task<DBusMessage> Handle(DBusMessage message, IDBusConnection connection, object target)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(connection);");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(target);");
        sb.AppendLine();
        sb.AppendLine($"            if (target is not {interfaceIdentifier} typedTarget)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return message.CreateError(\"org.freedesktop.DBus.Error.UnknownInterface\", \"Target does not implement interface {dBusInterface.Name}.\");");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                switch (message.Member)");
        sb.AppendLine("                {");

        foreach (var method in methods)
        {
            var inArgs = method.Arguments?.Where(static argument => argument.Direction is null or "in").ToArray() ?? Array.Empty<DBusArgument>();
            var outArgs = method.Arguments?.Where(static argument => argument.Direction == "out").ToArray() ?? Array.Empty<DBusArgument>();
            var methodIdentifier = GetInterfaceMethodIdentifier(method);
            var callArguments = string.Join(", ", inArgs.Select((argument, index) => GetParameterIdentifier(argument, index)));

            sb.AppendLine($"                    case {SymbolDisplay.FormatLiteral(method.Name!, quote: true)}:");
            sb.AppendLine("                    {");

            for (var i = 0; i < inArgs.Length; i++)
            {
                var parameterIdentifier = GetParameterIdentifier(inArgs[i], i);
                var fromDbusExpression = MakeFromDbusValueExpressionString(inArgs[i].DBusDotnetType, $"message.Body[{i}]");
                sb.AppendLine($"                        var {parameterIdentifier} = {fromDbusExpression};");
            }

            if (outArgs.Length == 0)
            {
                sb.AppendLine($"                        await typedTarget.{methodIdentifier}({callArguments}).ConfigureAwait(false);");
                sb.AppendLine("                        return message.CreateReply();");
            }
            else
            {
                sb.AppendLine($"                        var result = await typedTarget.{methodIdentifier}({callArguments}).ConfigureAwait(false);");

                if (outArgs.Length == 1)
                {
                    var toDbusExpression = MakeToDbusValueExpressionString(outArgs[0].DBusDotnetType, "result");
                    sb.AppendLine($"                        return message.CreateReply({toDbusExpression});");
                }
                else
                {
                    var replyArgs = string.Join(", ", outArgs.Select((argument, index) =>
                        MakeToDbusValueExpressionString(argument.DBusDotnetType, $"result.Item{index + 1}")));
                    sb.AppendLine($"                        return message.CreateReply({replyArgs});");
                }
            }

            sb.AppendLine("                    }");
        }

        sb.AppendLine("                    default:");
        sb.AppendLine("                        return message.CreateError(\"org.freedesktop.DBus.Error.UnknownMethod\", \"Unknown method\");");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                return message.CreateError(\"org.freedesktop.DBus.Error.InvalidArgs\", ex.Message);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static class {exportHelperIdentifier}");
        sb.AppendLine("    {");
        sb.AppendLine($"        private static readonly {dispatcherIdentifier} s_dispatcher = new();");
        sb.AppendLine("        private static readonly Func<DBusMessage, IDBusConnection, object, Task<DBusMessage>> s_dispatch = s_dispatcher.Handle;");
        sb.AppendLine($"        public const string InterfaceName = {interfaceNameLiteral};");
        sb.AppendLine();
        sb.AppendLine("        public static bool TryGetProperty(object target, string propertyName, out DBusVariant value)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(propertyName);");
        sb.AppendLine($"            if (target is not {interfaceIdentifier} typedTarget)");
        sb.AppendLine("            {");
        sb.AppendLine("                value = default!;");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            switch (propertyName)");
        sb.AppendLine("            {");
        foreach (var property in properties.Where(static p => p.Access is null or "read" or "readwrite"))
        {
            var propertyNameLiteral = SymbolDisplay.FormatLiteral(property.Name!, quote: true);
            var propertyIdentifier = GetPropertyIdentifier(property);
            var toDbusExpression = MakeToDbusValueExpressionString(property.DBusDotnetType, $"typedTarget.{propertyIdentifier}");
            sb.AppendLine($"                case {propertyNameLiteral}:");
            sb.AppendLine($"                    value = new DBusVariant({toDbusExpression});");
            sb.AppendLine("                    return true;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    value = default!;");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public static bool TrySetProperty(object target, string propertyName, DBusVariant value)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(propertyName);");
        sb.AppendLine($"            if (target is not {interfaceIdentifier} typedTarget)");
        sb.AppendLine("                return false;");
        sb.AppendLine();
        sb.AppendLine("            switch (propertyName)");
        sb.AppendLine("            {");
        foreach (var property in properties.Where(static p => p.Access is "write" or "readwrite"))
        {
            var propertyNameLiteral = SymbolDisplay.FormatLiteral(property.Name!, quote: true);
            var propertyIdentifier = GetPropertyIdentifier(property);
            var fromDbusExpression = MakeFromDbusValueExpressionString(property.DBusDotnetType, "value.Value");
            sb.AppendLine($"                case {propertyNameLiteral}:");
            sb.AppendLine($"                    typedTarget.{propertyIdentifier} = {fromDbusExpression};");
            sb.AppendLine("                    return true;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public static Dictionary<string, DBusVariant> GetAllProperties(object target)");
        sb.AppendLine("        {");
        sb.AppendLine("            var values = new Dictionary<string, DBusVariant>(StringComparer.Ordinal);");
        sb.AppendLine($"            if (target is not {interfaceIdentifier} typedTarget)");
        sb.AppendLine("                return values;");
        foreach (var property in properties.Where(static p => p.Access is null or "read" or "readwrite"))
        {
            var propertyNameLiteral = SymbolDisplay.FormatLiteral(property.Name!, quote: true);
            var propertyIdentifier = GetPropertyIdentifier(property);
            var toDbusExpression = MakeToDbusValueExpressionString(property.DBusDotnetType, $"typedTarget.{propertyIdentifier}");
            sb.AppendLine($"            values[{propertyNameLiteral}] = new DBusVariant({toDbusExpression});");
        }

        sb.AppendLine("            return values;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public static IDisposable Register(IDBusConnection connection, DBusObjectPath path, {interfaceIdentifier} target, SynchronizationContext? synchronizationContext = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(connection);");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(target);");
        sb.AppendLine("            return connection.RegisterObject(");
        sb.AppendLine("                path,");
        sb.AppendLine("                InterfaceName,");
        sb.AppendLine("                (registeredConnection, message) => s_dispatch(message, registeredConnection, target),");
        sb.AppendLine("                synchronizationContext);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static class {moduleInitializerIdentifier}");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        internal static void Register()");
        sb.AppendLine("        {");
        sb.AppendLine("            DBusWrapperMetadata.RegisterService(");
        sb.AppendLine($"                typeof({interfaceIdentifier}),");
        sb.AppendLine($"                {exportHelperIdentifier}.InterfaceName,");
        sb.AppendLine(
            $"                static (connection, path, target, synchronizationContext) => {exportHelperIdentifier}.Register(connection, path, ({interfaceIdentifier})target, synchronizationContext),");
        sb.AppendLine(
            $"                static (target, propertyName) => {exportHelperIdentifier}.TryGetProperty(target, propertyName, out var value) ? value : null,");
        sb.AppendLine(
            $"                static (target, propertyName, value) => {exportHelperIdentifier}.TrySetProperty(target, propertyName, value),");
        sb.AppendLine(
            $"                static target => {exportHelperIdentifier}.GetAllProperties(target));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetServiceInterfaceIdentifier(DBusInterface dBusInterface) => $"I{Pascalize(dBusInterface.Name!.AsSpan())}";

    private static string GetServiceDispatcherIdentifier(DBusInterface dBusInterface) => $"{Pascalize(dBusInterface.Name!.AsSpan())}Dispatcher";

    private static string GetServiceExportHelperIdentifier(DBusInterface dBusInterface) => $"{Pascalize(dBusInterface.Name!.AsSpan())}Export";

    private static string GetServiceModuleInitializerIdentifier(DBusInterface dBusInterface) => $"{Pascalize(dBusInterface.Name!.AsSpan())}ModuleInitializer";

    private static string GetInterfaceMethodIdentifier(DBusMethod method)
        => $"{Pascalize(method.Name!.AsSpan())}Async";

    private static string GetPropertyIdentifier(DBusProperty property)
        => SanitizeIdentifier(Pascalize(property.Name!.AsSpan()));

    private static string GetParameterIdentifier(DBusValue argument, int index)
        => argument.Name is not null
            ? SanitizeIdentifier(Camelize(argument.Name.AsSpan()))
            : $"arg{index}";

    private static string GetPropertyAccessors(string? access)
    {
        return access switch
        {
            null or "readwrite" => "get; set;",
            "read" => "get;",
            "write" => "set;",
            _ => string.Empty
        };
    }
}
