namespace Avalonia.DBus.SourceGen;

public partial class DBusSourceGenerator
{
    private const string BuiltInFreedesktopDbusSource = """
                                                          // <auto-generated/>
                                                          using System;
                                                          using System.Runtime.CompilerServices;
                                                          using System.Threading;
                                                          using System.Threading.Tasks;

                                                          #nullable enable
                                                          namespace Avalonia.DBus
                                                          {
                                                              public sealed class OrgFreedesktopDBusProxy
                                                              {
                                                                  private const string DefaultInterface = "org.freedesktop.DBus";
                                                                  private readonly IDBusConnection _connection;
                                                                  private readonly string _destination;
                                                                  private readonly DBusObjectPath _path;
                                                                  private readonly string _interface;

                                                                  public OrgFreedesktopDBusProxy(
                                                                      IDBusConnection connection,
                                                                      string destination,
                                                                      DBusObjectPath path)
                                                                      : this(connection, destination, path, DefaultInterface)
                                                                  {
                                                                  }

                                                                  public OrgFreedesktopDBusProxy(
                                                                      IDBusConnection connection,
                                                                      string destination,
                                                                      DBusObjectPath path,
                                                                      string iface)
                                                                  {
                                                                      _connection = connection ?? throw new ArgumentNullException(nameof(connection));
                                                                      _destination = destination ?? throw new ArgumentNullException(nameof(destination));
                                                                      _path = path;
                                                                      _interface = iface ?? throw new ArgumentNullException(nameof(iface));
                                                                  }

                                                                  public async Task<uint> RequestNameAsync(
                                                                      string name,
                                                                      uint flags,
                                                                      CancellationToken cancellationToken = default)
                                                                  {
                                                                      var reply = await _connection.CallMethodAsync(
                                                                          _destination,
                                                                          _path,
                                                                          _interface,
                                                                          "RequestName",
                                                                          cancellationToken,
                                                                          name,
                                                                          flags);
                                                                      return reply.Body[0] switch
                                                                      {
                                                                          uint u => u,
                                                                          int i => unchecked((uint)i),
                                                                          _ => throw new InvalidOperationException("RequestName returned an unexpected value.")
                                                                      };
                                                                  }

                                                                  public async Task<uint> ReleaseNameAsync(
                                                                      string name,
                                                                      CancellationToken cancellationToken = default)
                                                                  {
                                                                      var reply = await _connection.CallMethodAsync(
                                                                          _destination,
                                                                          _path,
                                                                          _interface,
                                                                          "ReleaseName",
                                                                          cancellationToken,
                                                                          name);
                                                                      return reply.Body[0] switch
                                                                      {
                                                                          uint u => u,
                                                                          int i => unchecked((uint)i),
                                                                          _ => throw new InvalidOperationException("ReleaseName returned an unexpected value.")
                                                                      };
                                                                  }

                                                                  public async Task<string> GetNameOwnerAsync(
                                                                      string name,
                                                                      CancellationToken cancellationToken = default)
                                                                  {
                                                                      var reply = await _connection.CallMethodAsync(
                                                                          _destination,
                                                                          _path,
                                                                          _interface,
                                                                          "GetNameOwner",
                                                                          cancellationToken,
                                                                          name);
                                                                      if (reply.Body.Count == 0 || reply.Body[0] is not string owner)
                                                                          throw new InvalidOperationException("GetNameOwner returned an unexpected value.");
                                                                      return owner;
                                                                  }

                                                                  public Task<IDisposable> WatchNameOwnerChangedAsync(
                                                                      Action<string, string?, string?> handler,
                                                                      string? sender = null,
                                                                      bool emitOnCapturedContext = true)
                                                                  {
                                                                      ArgumentNullException.ThrowIfNull(handler);
                                                                      return _connection.SubscribeAsync(
                                                                          sender,
                                                                          _path,
                                                                          _interface,
                                                                          "NameOwnerChanged",
                                                                          message =>
                                                                          {
                                                                              var name = (string)message.Body[0];
                                                                              var oldOwner = NormalizeNameOwner((string)message.Body[1]);
                                                                              var newOwner = NormalizeNameOwner((string)message.Body[2]);
                                                                              handler(name, oldOwner, newOwner);
                                                                              return Task.CompletedTask;
                                                                          },
                                                                          emitOnCapturedContext ? SynchronizationContext.Current : null);
                                                                  }

                                                                  public Task<IDisposable> WatchNameOwnerChangedAsync(
                                                                      Func<string, string?, string?, Task> handler,
                                                                      string? sender = null,
                                                                      bool emitOnCapturedContext = true)
                                                                  {
                                                                      ArgumentNullException.ThrowIfNull(handler);
                                                                      return _connection.SubscribeAsync(
                                                                          sender,
                                                                          _path,
                                                                          _interface,
                                                                          "NameOwnerChanged",
                                                                          message =>
                                                                          {
                                                                              var name = (string)message.Body[0];
                                                                              var oldOwner = NormalizeNameOwner((string)message.Body[1]);
                                                                              var newOwner = NormalizeNameOwner((string)message.Body[2]);
                                                                              return handler(name, oldOwner, newOwner);
                                                                          },
                                                                          emitOnCapturedContext ? SynchronizationContext.Current : null);
                                                                  }

                                                                  private static string? NormalizeNameOwner(string owner)
                                                                  {
                                                                      return string.IsNullOrWhiteSpace(owner) ? null : owner;
                                                                  }
                                                              }

                                                              public static class FreedesktopDBusExtensions
                                                              {
                                                                  private const string BusDestination = "org.freedesktop.DBus";
                                                                  private static readonly DBusObjectPath BusPath = (DBusObjectPath)"/org/freedesktop/DBus";

                                                                  public static OrgFreedesktopDBusProxy CreateFreedesktopDBusProxy(this IDBusConnection connection)
                                                                  {
                                                                      ArgumentNullException.ThrowIfNull(connection);
                                                                      return new OrgFreedesktopDBusProxy(connection, BusDestination, BusPath);
                                                                  }

                                                                  public static async Task<DBusRequestNameReply> RequestNameAsync(
                                                                      this IDBusConnection connection,
                                                                      string name,
                                                                      DBusRequestNameFlags flags = DBusRequestNameFlags.None,
                                                                      CancellationToken cancellationToken = default)
                                                                  {
                                                                      if (string.IsNullOrEmpty(name))
                                                                          throw new ArgumentException("Name is required.", nameof(name));

                                                                      var value = await connection
                                                                          .CreateFreedesktopDBusProxy()
                                                                          .RequestNameAsync(name, (uint)flags, cancellationToken);

                                                                      return (DBusRequestNameReply)value;
                                                                  }

                                                                  public static async Task ReleaseNameAsync(
                                                                      this IDBusConnection connection,
                                                                      string name,
                                                                      CancellationToken cancellationToken = default)
                                                                  {
                                                                      if (string.IsNullOrEmpty(name))
                                                                          throw new ArgumentException("Name is required.", nameof(name));

                                                                      _ = await connection
                                                                          .CreateFreedesktopDBusProxy()
                                                                          .ReleaseNameAsync(name, cancellationToken);
                                                                  }

                                                                  public static async Task<string?> GetNameOwnerAsync(
                                                                      this IDBusConnection connection,
                                                                      string name,
                                                                      CancellationToken cancellationToken = default)
                                                                  {
                                                                      if (string.IsNullOrEmpty(name))
                                                                          throw new ArgumentException("Name is required.", nameof(name));

                                                                      try
                                                                      {
                                                                          var owner = await connection
                                                                              .CreateFreedesktopDBusProxy()
                                                                              .GetNameOwnerAsync(name, cancellationToken);
                                                                          return string.IsNullOrWhiteSpace(owner) ? null : owner;
                                                                      }
                                                                      catch (DBusException ex) when (string.Equals(ex.ErrorName, "org.freedesktop.DBus.Error.NameHasNoOwner", StringComparison.Ordinal))
                                                                      {
                                                                          return null;
                                                                      }
                                                                  }

                                                                  public static Task<IDisposable> WatchNameOwnerChangedAsync(
                                                                      this IDBusConnection connection,
                                                                      Action<string, string?, string?> handler,
                                                                      bool emitOnCapturedContext = true,
                                                                      string? sender = null)
                                                                  {
                                                                      ArgumentNullException.ThrowIfNull(connection);
                                                                      return connection.CreateFreedesktopDBusProxy()
                                                                          .WatchNameOwnerChangedAsync(handler, sender, emitOnCapturedContext);
                                                                  }

                                                                  public static Task<IDisposable> WatchNameOwnerChangedAsync(
                                                                      this IDBusConnection connection,
                                                                      Func<string, string?, string?, Task> handler,
                                                                      bool emitOnCapturedContext = true,
                                                                      string? sender = null)
                                                                  {
                                                                      ArgumentNullException.ThrowIfNull(connection);
                                                                      return connection.CreateFreedesktopDBusProxy()
                                                                          .WatchNameOwnerChangedAsync(handler, sender, emitOnCapturedContext);
                                                                  }
                                                              }

                                                              internal static class FreedesktopDBusGeneratedPrivateImplementationDoNotTouch
                                                              {
                                                                  [ModuleInitializer]
                                                                  public static void Register()
                                                                  {
                                                                      DBusInteropMetadataRegistry.Register(
                                                                          new DBusInteropMetadata
                                                                          {
                                                                              ClrType = typeof(OrgFreedesktopDBusProxy),
                                                                              InterfaceName = "org.freedesktop.DBus",
                                                                              CreateProxy = static (connection, destination, path, iface) =>
                                                                                  new OrgFreedesktopDBusProxy(connection, destination, path, iface)
                                                                          });
                                                                  }
                                                              }
                                                          }
                                                          """;
}
