using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;


namespace Avalonia.DBus.SourceGen;

public partial class DBusSourceGenerator
{
    private static CompilationUnitSyntax MakeCompilationUnit(NamespaceDeclarationSyntax namespaceDeclaration) =>
        CompilationUnit()
            .AddUsings(
                UsingDirective(
                    IdentifierName("System")),
                UsingDirective(
                    IdentifierName("System.Collections.Generic")),
                UsingDirective(
                    IdentifierName("System.Linq")),
                UsingDirective(
                    IdentifierName("System.Threading")),
                UsingDirective(
                    IdentifierName("System.Threading.Tasks")),
                UsingDirective(
                    IdentifierName("System.Xml")),
                UsingDirective(
                    IdentifierName("Avalonia.DBus")))
            .WithLeadingTrivia(
                Comment("// <auto-generated>"))
            .AddMembers(namespaceDeclaration
                .WithLeadingTrivia(
                    TriviaList(
                        Trivia(
                            PragmaWarningDirectiveTrivia(
                                Token(SyntaxKind.DisableKeyword), true)),
                        Trivia(
                            NullableDirectiveTrivia(
                                Token(SyntaxKind.EnableKeyword), true)))))
            .NormalizeWhitespace();

    private static FieldDeclarationSyntax MakePrivateStringConst(string identifier, string value, TypeSyntax type) =>
        FieldDeclaration(
                VariableDeclaration(type)
                    .AddVariables(
                        VariableDeclarator(identifier)
                            .WithInitializer(
                                EqualsValueClause(
                                    MakeLiteralExpression(value)))))
            .AddModifiers(
                Token(SyntaxKind.PrivateKeyword),
                Token(SyntaxKind.ConstKeyword));

    private static FieldDeclarationSyntax MakePrivateReadOnlyField(string identifier, TypeSyntax type) =>
        FieldDeclaration(
                VariableDeclaration(type)
                    .AddVariables(
                        VariableDeclarator(identifier)))
            .AddModifiers(
                Token(SyntaxKind.PrivateKeyword),
                Token(SyntaxKind.ReadOnlyKeyword));

    private static PropertyDeclarationSyntax MakeGetOnlyProperty(TypeSyntax type, string identifier, params SyntaxToken[] modifiers) =>
        PropertyDeclaration(type, identifier)
            .AddModifiers(modifiers)
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                    .WithSemicolonToken(
                        Token(SyntaxKind.SemicolonToken)));

    private static PropertyDeclarationSyntax MakeGetSetProperty(TypeSyntax type, string identifier, params SyntaxToken[] modifiers) =>
        PropertyDeclaration(type, identifier)
            .AddModifiers(modifiers)
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                    .WithSemicolonToken(
                        Token(SyntaxKind.SemicolonToken)),
                AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                    .WithSemicolonToken(
                        Token(SyntaxKind.SemicolonToken)));

    private static ExpressionStatementSyntax MakeAssignmentExpressionStatement(string left, string right) =>
        ExpressionStatement(
            MakeAssignmentExpression(
                IdentifierName(left),
                IdentifierName(right)));

    private static AssignmentExpressionSyntax MakeAssignmentExpression(ExpressionSyntax left, ExpressionSyntax right) => AssignmentExpression(SyntaxKind.SimpleAssignmentExpression, left, right);

    private static MemberAccessExpressionSyntax MakeMemberAccessExpression(string left, string right) => MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, IdentifierName(left), IdentifierName(right));

    private static MemberAccessExpressionSyntax MakeMemberAccessExpression(string left, string middle, string right) =>
        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, MakeMemberAccessExpression(left, middle), IdentifierName(right));

    private static LiteralExpressionSyntax MakeLiteralExpression(string literal) => LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(literal));
}
