using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Avalonia.DBus.SourceGen;

public partial class DBusSourceGenerator
{
    private static string BuildServiceSource(DBusInterface dBusInterface)
    {
        var interfaceIdentifier = GetServiceInterfaceIdentifier(dBusInterface);
        var dispatcherIdentifier = GetServiceDispatcherIdentifier(dBusInterface);
        var descriptorHolderIdentifier = GetServiceDescriptorHolderIdentifier(dBusInterface);
        var exportHelperIdentifier = GetServiceExportHelperIdentifier(dBusInterface);
        var moduleInitializerIdentifier = GetServiceModuleInitializerIdentifier(dBusInterface);

        var interfaceNameLiteral = SymbolDisplay.FormatLiteral(dBusInterface.Name!, quote: true);
        var introspectionLiteral = SymbolDisplay.FormatLiteral(BuildInterfaceIntrospectionXml(dBusInterface), quote: true);

        var properties = dBusInterface.Properties ?? Array.Empty<DBusProperty>();
        var methods = dBusInterface.Methods ?? Array.Empty<DBusMethod>();

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Avalonia.DBus;");
        sb.AppendLine();
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Avalonia.DBus.SourceGen");
        sb.AppendLine("{");

        sb.AppendLine($"    internal interface {interfaceIdentifier}");
        sb.AppendLine("    {");
        foreach (var property in properties)
        {
            var access = GetPropertyAccessors(property.Access);
            if (string.IsNullOrEmpty(access))
                continue;

            var propertyType = property.DBusDotnetType.ToTypeSyntax().ToString();
            var propertyIdentifier = GetPropertyIdentifier(property);
            sb.AppendLine($"        {propertyType} {propertyIdentifier} {{ {access} }}");
        }

        foreach (var method in methods)
        {
            var inArgs = method.Arguments?.Where(static argument => argument.Direction is null or "in").ToArray() ?? Array.Empty<DBusArgument>();
            var outArgs = method.Arguments?.Where(static argument => argument.Direction == "out").ToArray() ?? Array.Empty<DBusArgument>();
            var returnType = ParseValueTaskReturnType(outArgs).NormalizeWhitespace().ToFullString();
            var parameterList = string.Join(", ", inArgs.Select((argument, index) =>
                $"{argument.DBusDotnetType.ToTypeSyntax()} {GetParameterIdentifier(argument, index)}"));
            sb.AppendLine($"        {returnType} {GetInterfaceMethodIdentifier(method)}({parameterList});");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal sealed class {dispatcherIdentifier} : IDBusInterfaceCallDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        public async Task<DBusMessage> Handle(DBusMessage message, DBusConnection connection, object target)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(connection);");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(target);");
        sb.AppendLine();
        sb.AppendLine($"            if (target is not {interfaceIdentifier} typedTarget)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return message.CreateError(\"org.freedesktop.DBus.Error.UnknownInterface\", \"Target does not implement interface {dBusInterface.Name}.\");");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                switch (message.Member)");
        sb.AppendLine("                {");

        foreach (var method in methods)
        {
            var inArgs = method.Arguments?.Where(static argument => argument.Direction is null or "in").ToArray() ?? Array.Empty<DBusArgument>();
            var outArgs = method.Arguments?.Where(static argument => argument.Direction == "out").ToArray() ?? Array.Empty<DBusArgument>();
            var methodIdentifier = GetInterfaceMethodIdentifier(method);
            var callArguments = string.Join(", ", inArgs.Select((argument, index) => GetParameterIdentifier(argument, index)));

            sb.AppendLine($"                    case {SymbolDisplay.FormatLiteral(method.Name!, quote: true)}:");
            sb.AppendLine("                    {");

            for (var i = 0; i < inArgs.Length; i++)
            {
                var parameterIdentifier = GetParameterIdentifier(inArgs[i], i);
                var fromDbusExpression = MakeFromDbusValueExpressionString(inArgs[i].DBusDotnetType, $"message.Body[{i}]");
                sb.AppendLine($"                        var {parameterIdentifier} = {fromDbusExpression};");
            }

            if (outArgs.Length == 0)
            {
                sb.AppendLine($"                        await typedTarget.{methodIdentifier}({callArguments}).ConfigureAwait(false);");
                sb.AppendLine("                        return message.CreateReply();");
            }
            else
            {
                sb.AppendLine($"                        var result = await typedTarget.{methodIdentifier}({callArguments}).ConfigureAwait(false);");

                if (outArgs.Length == 1)
                {
                    var toDbusExpression = MakeToDbusValueExpressionString(outArgs[0].DBusDotnetType, "result");
                    sb.AppendLine($"                        return message.CreateReply({toDbusExpression});");
                }
                else
                {
                    var replyArgs = string.Join(", ", outArgs.Select((argument, index) =>
                        MakeToDbusValueExpressionString(argument.DBusDotnetType, $"result.Item{index + 1}")));
                    sb.AppendLine($"                        return message.CreateReply({replyArgs});");
                }
            }

            sb.AppendLine("                    }");
        }

        sb.AppendLine("                    default:");
        sb.AppendLine("                        return message.CreateError(\"org.freedesktop.DBus.Error.UnknownMethod\", \"Unknown method\");");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                return message.CreateError(\"org.freedesktop.DBus.Error.InvalidArgs\", ex.Message);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static class {descriptorHolderIdentifier}");
        sb.AppendLine("    {");
        sb.AppendLine($"        private static readonly IDBusInterfaceCallDispatcher s_dispatcher = new {dispatcherIdentifier}();");
        sb.AppendLine();
        sb.AppendLine("        internal static DBusInterfaceDescriptor Instance { get; } =");
        sb.AppendLine("            new DBusInterfaceDescriptor");
        sb.AppendLine("            {");
        sb.AppendLine($"                InterfaceName = {interfaceNameLiteral},");
        sb.AppendLine($"                ClrInterfaceType = typeof({interfaceIdentifier}),");
        sb.AppendLine($"                IntrospectionXml = {introspectionLiteral},");
        sb.AppendLine("                Dispatcher = s_dispatcher,");

        sb.AppendLine("                Properties = new Dictionary<string, DBusPropertyDescriptor>(StringComparer.Ordinal)");
        sb.AppendLine("                {");
        foreach (var property in properties)
        {
            var propertyNameLiteral = SymbolDisplay.FormatLiteral(property.Name!, quote: true);
            var propertyIdentifier = GetPropertyIdentifier(property);
            var signatureLiteral = SymbolDisplay.FormatLiteral(property.DBusDotnetType.DBusTypeSignature, quote: true);
            var canRead = property.Access is null or "read" or "readwrite";
            var canWrite = property.Access is null or "write" or "readwrite";

            sb.AppendLine($"                    [{propertyNameLiteral}] = new DBusPropertyDescriptor");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = {propertyNameLiteral},");
            sb.AppendLine($"                        CanRead = {(canRead ? "true" : "false")},");
            sb.AppendLine($"                        CanWrite = {(canWrite ? "true" : "false")},");
            sb.AppendLine($"                        Signature = {signatureLiteral},");

            if (canRead)
            {
                var toDbusExpression = MakeToDbusValueExpressionString(property.DBusDotnetType, $"typedTarget.{propertyIdentifier}");
                sb.AppendLine("                        TryGet = static (object target, out DBusVariant value) =>");
                sb.AppendLine("                        {");
                sb.AppendLine($"                            if (target is {interfaceIdentifier} typedTarget)");
                sb.AppendLine("                            {");
                sb.AppendLine($"                                value = new DBusVariant({toDbusExpression});");
                sb.AppendLine("                                return true;");
                sb.AppendLine("                            }");
                sb.AppendLine();
                sb.AppendLine("                            value = null!;");
                sb.AppendLine("                            return false;");
                sb.AppendLine("                        },");
            }
            else
            {
                sb.AppendLine("                        TryGet = null,");
            }

            if (canWrite)
            {
                var fromDbusExpression = MakeFromDbusValueExpressionString(property.DBusDotnetType, "value.Value");
                sb.AppendLine("                        TrySet = static (object target, DBusVariant value) =>");
                sb.AppendLine("                        {");
                sb.AppendLine($"                            if (target is not {interfaceIdentifier} typedTarget)");
                sb.AppendLine("                                return false;");
                sb.AppendLine();
                sb.AppendLine($"                            typedTarget.{propertyIdentifier} = {fromDbusExpression};");
                sb.AppendLine("                            return true;");
                sb.AppendLine("                        }");
            }
            else
            {
                sb.AppendLine("                        TrySet = null");
            }

            sb.AppendLine("                    },");
        }
        sb.AppendLine("                },");

        sb.AppendLine("                Methods = new Dictionary<string, DBusMethodDescriptor>(StringComparer.Ordinal)");
        sb.AppendLine("                {");
        foreach (var method in methods)
        {
            var methodNameLiteral = SymbolDisplay.FormatLiteral(method.Name!, quote: true);
            var inSignatureLiteral = SymbolDisplay.FormatLiteral(GetMethodInSignature(method), quote: true);
            var outSignatureLiteral = SymbolDisplay.FormatLiteral(GetMethodOutSignature(method), quote: true);

            sb.AppendLine($"                    [{methodNameLiteral}] = new DBusMethodDescriptor");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = {methodNameLiteral},");
            sb.AppendLine($"                        InSignature = {inSignatureLiteral},");
            sb.AppendLine($"                        OutSignature = {outSignatureLiteral}");
            sb.AppendLine("                    },");
        }
        sb.AppendLine("                }");
        sb.AppendLine("            }; ");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static class {exportHelperIdentifier}");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static void Bind(DBusExportedTargetBindingBuilder builder, {interfaceIdentifier} target, SynchronizationContext? synchronizationContext = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            ArgumentNullException.ThrowIfNull(builder);");
        sb.AppendLine($"            builder.Bind<{interfaceIdentifier}>(target, synchronizationContext);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public static DBusExportedTarget CreateTarget({interfaceIdentifier} target, SynchronizationContext? synchronizationContext = null)");
        sb.AppendLine("            => DBusExportedTarget.Create(target, builder => Bind(builder, target, synchronizationContext));");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static class {moduleInitializerIdentifier}");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        internal static void Register()");
        sb.AppendLine("        {");
        sb.AppendLine($"            DBusGeneratedMetadata.Register({descriptorHolderIdentifier}.Instance);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetServiceInterfaceIdentifier(DBusInterface dBusInterface) => $"I{Pascalize(dBusInterface.Name!.AsSpan())}";

    private static string GetServiceDispatcherIdentifier(DBusInterface dBusInterface) => $"{Pascalize(dBusInterface.Name!.AsSpan())}Dispatcher";

    private static string GetServiceDescriptorHolderIdentifier(DBusInterface dBusInterface) => $"{Pascalize(dBusInterface.Name!.AsSpan())}Descriptor";

    private static string GetServiceExportHelperIdentifier(DBusInterface dBusInterface) => $"{Pascalize(dBusInterface.Name!.AsSpan())}Export";

    private static string GetServiceModuleInitializerIdentifier(DBusInterface dBusInterface) => $"{Pascalize(dBusInterface.Name!.AsSpan())}ModuleInitializer";

    private static string BuildInterfaceIntrospectionXml(DBusInterface dBusInterface)
    {
        XmlSerializer xmlSerializer = new(typeof(DBusInterface));
        using StringWriter stringWriter = new();
        using var xmlWriter = XmlWriter.Create(stringWriter, new XmlWriterSettings
        {
            OmitXmlDeclaration = true,
            Indent = true
        });

        xmlSerializer.Serialize(xmlWriter, dBusInterface);
        return stringWriter.ToString();
    }

    private static string GetMethodInSignature(DBusMethod method)
    {
        if (method.Arguments == null || method.Arguments.Length == 0)
            return string.Empty;

        return string.Concat(method.Arguments
            .Where(static argument => argument.Direction is null or "in")
            .Select(static argument => argument.DBusDotnetType.DBusTypeSignature));
    }

    private static string GetMethodOutSignature(DBusMethod method)
    {
        if (method.Arguments == null || method.Arguments.Length == 0)
            return string.Empty;

        return string.Concat(method.Arguments
            .Where(static argument => argument.Direction == "out")
            .Select(static argument => argument.DBusDotnetType.DBusTypeSignature));
    }

    private static string GetInterfaceMethodIdentifier(DBusMethod method)
        => $"{Pascalize(method.Name!.AsSpan())}Async";

    private static string GetPropertyIdentifier(DBusProperty property)
        => SanitizeIdentifier(Pascalize(property.Name!.AsSpan()));

    private static string GetParameterIdentifier(DBusValue argument, int index)
        => argument.Name is not null
            ? SanitizeIdentifier(Camelize(argument.Name.AsSpan()))
            : $"arg{index}";

    private static string GetPropertyAccessors(string? access)
    {
        return access switch
        {
            null or "readwrite" => "get; set;",
            "read" => "get;",
            "write" => "set;",
            _ => string.Empty
        };
    }
}
